"""Exact branch and repair-reason contract for semantic classifiers."""

from __future__ import annotations

import pytest

from agent_maintainer.contracts.classifiers import classify_change
from agent_maintainer.contracts.models import Classification, ContractKind

Result = tuple[Classification, str]
Case = tuple[ContractKind, str, str, object | None, object | None, str]

EXPECTED: dict[str, Result] = {
    "unknown": ("review-required", "unrecognized semantic operation"),
    "contract-add": ("compatible", "new contract surface"),
    "removal": ("breaking", "contract surface removed"),
    "config-required": ("breaking", "new required configuration field"),
    "config-default": (
        "compatible",
        "new optional configuration field with default",
    ),
    "config-ambiguous": (
        "review-required",
        "new optional configuration field has no explicit default",
    ),
    "command": ("compatible", "new command surface"),
    "command-required": ("breaking", "new required command input"),
    "command-optional": ("compatible", "new optional command input"),
    "python-member": ("compatible", "new nominated Python API member"),
    "python-optional": ("compatible", "new optional Python parameter"),
    "python-required": ("breaking", "new required Python parameter"),
    "schema-required": ("breaking", "new required schema property"),
    "schema-optional": ("compatible", "new optional schema property"),
    "rename-alias": (
        "compatible",
        "renamed member preserves its previous name as an alias",
    ),
    "rename-ambiguous": (
        "review-required",
        "inferred member rename has no proved alias mapping",
    ),
    "annotation": ("review-required", "annotation compatibility is not provable"),
    "type-widened": ("compatible", "accepted type set widened"),
    "type-broken": (
        "breaking",
        "accepted type set narrowed or changed incompatibly",
    ),
    "kind-broken": ("breaking", "value kind changed incompatibly"),
    "became-required": ("breaking", "optional member became required"),
    "became-optional": ("compatible", "required member became optional"),
    "required-ambiguous": ("review-required", "requiredness change is ambiguous"),
    "default-gained": ("compatible", "parameter gained a default"),
    "default-lost": ("breaking", "parameter lost its default"),
    "public-default": ("breaking", "public default changed"),
    "default-ambiguous": (
        "review-required",
        "literal default compatibility is not provable",
    ),
    "alias-added": ("compatible", "new alias preserves canonical identity"),
    "alias-removed": ("breaking", "supported alias removed"),
    "alias-ambiguous": (
        "review-required",
        "aliases changed incompatibly or conflict",
    ),
    "additional-broken": (
        "breaking",
        "additional properties are no longer accepted",
    ),
    "additional-relaxed": ("compatible", "additional properties are now accepted"),
    "additional-ambiguous": (
        "review-required",
        "additional-property compatibility is not provable",
    ),
    "exclusive-broken": ("breaking", "constraint became exclusive"),
    "exclusive-relaxed": ("compatible", "exclusive constraint was relaxed"),
    "exclusive-ambiguous": (
        "review-required",
        "constraint exclusivity is not provable",
    ),
    "values-broken": ("breaking", "accepted values changed incompatibly"),
    "enum-expanded": (
        "review-required",
        "enum expanded for potentially exhaustive consumers",
    ),
    "enum-removed": ("breaking", "accepted enum values were removed"),
    "enum-ambiguous": ("review-required", "enum values changed incompatibly"),
    "range-broken": ("breaking", "accepted range narrowed"),
    "range-relaxed": ("compatible", "accepted range widened"),
    "range-added": (
        "breaking",
        "new range constraint narrows accepted values",
    ),
    "range-removed": ("compatible", "range constraint was removed"),
    "range-ambiguous": ("review-required", "range compatibility is not provable"),
    "mapping-broken": (
        "breaking",
        "one or more accepted-value constraints tightened",
    ),
    "mapping-review": (
        "review-required",
        "one or more constraint changes require review",
    ),
    "mapping-relaxed": (
        "compatible",
        "accepted-value constraints were relaxed",
    ),
    "literal": (
        "review-required",
        "exported literal compatibility is not provable",
    ),
    "constraint-review": (
        "review-required",
        "constraint compatibility is not provable",
    ),
    "order": ("breaking", "positional member order changed"),
    "unsupported": ("review-required", "unsupported semantics changed"),
}

CASES: tuple[Case, ...] = (
    ("config-capabilities", "unknown", "/x", 1, 2, "unknown"),
    ("config-capabilities", "contract-add", "/new", None, {}, "contract-add"),
    ("config-capabilities", "contract-remove", "/old", {}, None, "removal"),
    ("config-capabilities", "member-add", "/fields/x", None, {"required": True}, "config-required"),
    ("config-capabilities", "member-add", "/fields/x", None, {"default": 0}, "config-default"),
    ("config-capabilities", "member-add", "/fields/x", None, {}, "config-ambiguous"),
    ("cli-manifest", "member-add", "/commands/new", None, {}, "command"),
    (
        "cli-manifest",
        "member-add",
        "/commands/x/options/y",
        None,
        {"required": True},
        "command-required",
    ),
    ("cli-manifest", "member-add", "/commands/x/arguments/y", None, {}, "command-optional"),
    ("python-api", "member-add", "/exports/new", None, {}, "python-member"),
    (
        "python-api",
        "member-add",
        "/exports/f/parameters/x",
        None,
        {"has_default": True},
        "python-optional",
    ),
    (
        "python-api",
        "member-add",
        "/exports/f/parameters/a",
        None,
        {"kind": "var-positional"},
        "python-optional",
    ),
    (
        "python-api",
        "member-add",
        "/exports/f/parameters/k",
        None,
        {"kind": "var-keyword"},
        "python-optional",
    ),
    (
        "python-api",
        "member-add",
        "/exports/f/parameters/x",
        None,
        {"kind": "keyword-only"},
        "python-required",
    ),
    ("json-schema", "member-add", "/properties/x", None, {"required": True}, "schema-required"),
    ("json-schema", "member-add", "/properties/x", None, {}, "schema-optional"),
    (
        "json-schema",
        "member-rename",
        "/properties/new",
        {"name": "old"},
        {"aliases": ("old",)},
        "rename-alias",
    ),
    (
        "json-schema",
        "member-rename",
        "/properties/new",
        {"name": "old"},
        {"aliases": ["other"]},
        "rename-ambiguous",
    ),
    (
        "python-api",
        "type-change",
        "/exports/f/parameters/x/annotation",
        "str",
        "object",
        "annotation",
    ),
    ("python-api", "type-change", "/exports/f/return_annotation", "str", "object", "annotation"),
    (
        "json-schema",
        "type-change",
        "/properties/x/types",
        ["string"],
        ["null", "string"],
        "type-widened",
    ),
    (
        "json-schema",
        "type-change",
        "/properties/x/types",
        ("null", "string"),
        ("string",),
        "type-broken",
    ),
    ("json-schema", "type-change", "/properties/x/types", ["string"], ["integer"], "type-broken"),
    ("json-schema", "type-change", "/properties/x/types", ["string"], ["string"], "kind-broken"),
    ("json-schema", "type-change", "/properties/x/kind", None, "object", "kind-broken"),
    ("json-schema", "requiredness-change", "/required", False, True, "became-required"),
    ("json-schema", "requiredness-change", "/required", True, False, "became-optional"),
    ("json-schema", "requiredness-change", "/required", None, False, "required-ambiguous"),
    ("json-schema", "requiredness-change", "/required", False, False, "required-ambiguous"),
    ("python-api", "default-change", "/has_default", False, True, "default-gained"),
    ("python-api", "default-change", "/has_default", True, False, "default-lost"),
    ("config-capabilities", "default-change", "/default", 1, 2, "public-default"),
    ("cli-manifest", "default-change", "/default", "a", "b", "public-default"),
    ("python-api", "default-change", "/default", 1, 2, "default-ambiguous"),
    ("json-schema", "alias-change", "/aliases", ["old"], ["legacy", "old"], "alias-added"),
    ("json-schema", "alias-change", "/aliases", ["legacy", "old"], ["old"], "alias-removed"),
    ("json-schema", "alias-change", "/aliases", ["old"], ["new"], "alias-ambiguous"),
    ("json-schema", "alias-change", "/aliases", ["old"], ["old"], "alias-ambiguous"),
    (
        "json-schema",
        "constraint-change",
        "/additional_properties",
        True,
        False,
        "additional-broken",
    ),
    (
        "json-schema",
        "constraint-change",
        "/additional_properties",
        False,
        True,
        "additional-relaxed",
    ),
    (
        "json-schema",
        "constraint-change",
        "/additional_properties",
        True,
        True,
        "additional-ambiguous",
    ),
    ("json-schema", "constraint-change", "/minimum_exclusive", False, True, "exclusive-broken"),
    ("json-schema", "constraint-change", "/maximum_exclusive", True, False, "exclusive-relaxed"),
    ("json-schema", "constraint-change", "/minimum_exclusive", None, None, "exclusive-ambiguous"),
    ("json-schema", "constraint-change", "/const", "old", "new", "values-broken"),
    ("json-schema", "constraint-change", "/pattern", "a", "b", "values-broken"),
    (
        "json-schema",
        "constraint-change",
        "/enum",
        [{"v": "a"}],
        [{"v": "a"}, {"v": "b"}],
        "enum-expanded",
    ),
    ("json-schema", "constraint-change", "/choices", ["a", "b"], ["a"], "enum-removed"),
    ("json-schema", "constraint-change", "/enum", ["a"], ["b"], "enum-ambiguous"),
    ("json-schema", "constraint-change", "/enum", ["a"], ["a"], "enum-ambiguous"),
    ("json-schema", "constraint-change", "/min_length", 2, 3, "range-broken"),
    ("json-schema", "constraint-change", "/exclusive_maximum", 10, 8, "range-broken"),
    ("json-schema", "constraint-change", "/exclusive_minimum", 1, 2, "range-broken"),
    ("json-schema", "constraint-change", "/min_items", 1, 2, "range-broken"),
    ("json-schema", "constraint-change", "/minimum", 3, 2, "range-relaxed"),
    ("json-schema", "constraint-change", "/maximum", 10, 8, "range-broken"),
    ("json-schema", "constraint-change", "/max_items", 8, 10, "range-relaxed"),
    ("json-schema", "constraint-change", "/minimum", 2, 2, "range-relaxed"),
    ("json-schema", "constraint-change", "/maximum", 10, 10, "range-relaxed"),
    ("json-schema", "constraint-change", "/minimum", None, 1, "range-added"),
    ("json-schema", "constraint-change", "/maximum", 10, None, "range-removed"),
    ("json-schema", "constraint-change", "/minimum", "low", "high", "range-ambiguous"),
    (
        "json-schema",
        "constraint-change",
        "/constraints",
        {"min_length": 1},
        {"min_length": 2},
        "mapping-broken",
    ),
    (
        "json-schema",
        "constraint-change",
        "/constraints",
        {"format": "date"},
        {"format": "date-time"},
        "mapping-review",
    ),
    (
        "json-schema",
        "constraint-change",
        "/constraints",
        {"max_length": 5},
        {"max_length": 6},
        "mapping-relaxed",
    ),
    ("python-api", "constraint-change", "/exports/x/value", 1, 2, "literal"),
    (
        "json-schema",
        "constraint-change",
        "/properties/x/format",
        "date",
        "date-time",
        "constraint-review",
    ),
    ("python-api", "constraint-change", "/parameters/order", ["a", "b"], ["b", "a"], "order"),
    ("json-schema", "unsupported-semantic-change", "/unsupported", [], ["/oneOf"], "unsupported"),
    ("python-api", "default-change", "/has_default", False, False, "default-ambiguous"),
    ("python-api", "default-change", "/has_default", True, True, "default-ambiguous"),
    ("json-schema", "constraint-change", "/constraints", None, {}, "constraint-review"),
    (
        "json-schema",
        "constraint-change",
        "/format",
        {"min_length": 1},
        {"min_length": 2},
        "constraint-review",
    ),
    ("python-api", "constraint-change", "/exports/x/format", "a", "b", "constraint-review"),
    ("json-schema", "constraint-change", "/minimum_exclusive", False, False, "exclusive-ambiguous"),
    ("json-schema", "constraint-change", "/minimum_exclusive", True, True, "exclusive-ambiguous"),
    ("json-schema", "constraint-change", "/constraints", {}, {"min_length": 1}, "mapping-broken"),
    ("json-schema", "constraint-change", "/constraints", {"format": "date"}, {}, "mapping-review"),
)


@pytest.mark.parametrize("case", CASES)
def test_exact_classifier_branches_and_repair_reasons(case: Case) -> None:
    """Every supported branch preserves classification and repair wording."""
    kind, operation, path, before, after, expected_key = case
    assert classify_change(kind, operation, path, before, after) == EXPECTED[expected_key]
