"""Starter repository files for package-first initialization."""

from __future__ import annotations

import textwrap
from dataclasses import dataclass

from ai_guardrails.core.init_template_config import STARTER_PYPROJECT

CORE_TRACK = "core"
AGENT_TRACK = "agent"
HARDENING_TRACK = "hardening"
TRACKS = (CORE_TRACK, AGENT_TRACK, HARDENING_TRACK)

PRE_COMMIT_CONFIG = textwrap.dedent(
    """\
    repos:
      - repo: local
        hooks:
          - id: ai-guardrails-precommit
            name: ai guardrails precommit
            entry: >-
              env PYTHONDONTWRITEBYTECODE=1 python3 -m ai_guardrails
              verify --profile precommit --base-ref HEAD --staged
            language: system
            pass_filenames: false
    """
)

WORKFLOW = textwrap.dedent(
    """\
    name: verify

    on:
      pull_request:
      push:
        branches: [main]

    permissions:
      contents: read

    jobs:
      verify:
        runs-on: ubuntu-latest
        env:
          PYTHONDONTWRITEBYTECODE: "1"
        steps:
          - name: Checkout
            uses: actions/checkout@v7
            with:
              fetch-depth: 0
              persist-credentials: false
          - name: Set up Python
            uses: actions/setup-python@v6.2.0
            with:
              python-version: "3.13"
          - name: Install project and guardrail tools
            run: |
              python -m pip install --upgrade pip
              if [ -f config/dev-lock.txt ]; then
                python -m pip install -r config/dev-lock.txt
              elif [ -f config/dev-dependencies.txt ]; then
                python -m pip install -r config/dev-dependencies.txt
              fi
              python -m pip install -e . --no-deps
          - name: Verify
            run: python3 -m ai_guardrails verify --profile ci
    """
)

AGENTS = textwrap.dedent(
    """\
    # Repository guardrails

    Read `AGENTS.guardrails.md` before changing code when it exists. That file
    is generated by `python3 -m ai_guardrails guidance` from
    `[tool.ai_guardrails]`.

    Before finishing a code change, run:

    ```bash
    python3 -m ai_guardrails verify --profile precommit
    ```

    For larger changes, also run:

    ```bash
    python3 -m ai_guardrails verify --profile full
    ```
    """
)

CODEX_CONFIG = textwrap.dedent(
    """\
    [features]
    hooks = true

    [[hooks.PostToolUse]]
    matcher = "apply_patch|Edit|Write"

    [[hooks.PostToolUse.hooks]]
    type = "command"
    command = 'python3 "$(git rev-parse --show-toplevel)/.codex/hooks/post_edit_fast_gate.py"'
    timeout = 60
    statusMessage = "Running fast Python guardrails"

    [[hooks.Stop]]

    [[hooks.Stop.hooks]]
    type = "command"
    command = 'python3 "$(git rev-parse --show-toplevel)/.codex/hooks/stop_full_verify.py"'
    timeout = 600
    statusMessage = "Running final verification"
    """
)

POST_EDIT_HOOK = textwrap.dedent(
    """\
    \"\"\"Codex PostToolUse hook: run fast package guardrails.\"\"\"

    from __future__ import annotations

    import json
    import os
    import subprocess  # nosec B404
    import sys
    from pathlib import Path

    sys.dont_write_bytecode = True


    def verifier_python(repo_root: Path) -> str:
        for relative in (".venv/bin/python", "venv/bin/python"):
            candidate = repo_root / relative
            if candidate.exists():
                return str(candidate)
        return sys.executable


    def verifier_env(repo_root: Path) -> dict[str, str]:
        env = dict(os.environ)
        env.setdefault("PYTHONDONTWRITEBYTECODE", "1")
        src_path = str(repo_root / "src")
        pythonpath = env.get("PYTHONPATH")
        env["PYTHONPATH"] = f"{src_path}{os.pathsep}{pythonpath}" if pythonpath else src_path
        return env


    def main() -> int:
        repo_root = Path(__file__).resolve().parents[2]
        command = [
            verifier_python(repo_root),
            "-m",
            "ai_guardrails",
            "verify",
            "--profile",
            "fast",
            "--base-ref",
            "HEAD",
        ]
        result = subprocess.run(
            command,
            cwd=repo_root,
            env=verifier_env(repo_root),
            text=True,
            capture_output=True,
            check=False,
        )
        if result.returncode == 0:
            return 0
        output = (result.stdout or result.stderr or "Verification failed.").strip()
        print(
            json.dumps(
                {
                    "decision": "block",
                    "reason": "Fast repository guardrails failed.",
                    "hookSpecificOutput": {
                        "hookEventName": "PostToolUse",
                        "additionalContext": output[:6000],
                    },
                }
            )
        )
        return 0


    if __name__ == "__main__":
        sys.exit(main())
    """
)

STOP_HOOK = textwrap.dedent(
    """\
    \"\"\"Codex Stop hook: run precommit package guardrails.\"\"\"

    from __future__ import annotations

    import json
    import os
    import subprocess  # nosec B404
    import sys
    from pathlib import Path

    sys.dont_write_bytecode = True


    def verifier_python(repo_root: Path) -> str:
        for relative in (".venv/bin/python", "venv/bin/python"):
            candidate = repo_root / relative
            if candidate.exists():
                return str(candidate)
        return sys.executable


    def verifier_env(repo_root: Path) -> dict[str, str]:
        env = dict(os.environ)
        env.setdefault("PYTHONDONTWRITEBYTECODE", "1")
        src_path = str(repo_root / "src")
        pythonpath = env.get("PYTHONPATH")
        env["PYTHONPATH"] = f"{src_path}{os.pathsep}{pythonpath}" if pythonpath else src_path
        return env


    def main() -> int:
        try:
            payload = json.load(sys.stdin)
        except json.JSONDecodeError:
            payload = {}
        if payload.get("stop_hook_active") is True:
            print(json.dumps({"continue": True}))
            return 0
        repo_root = Path(__file__).resolve().parents[2]
        command = [
            verifier_python(repo_root),
            "-m",
            "ai_guardrails",
            "verify",
            "--profile",
            "precommit",
            "--base-ref",
            "HEAD",
        ]
        result = subprocess.run(
            command,
            cwd=repo_root,
            env=verifier_env(repo_root),
            text=True,
            capture_output=True,
            check=False,
        )
        if result.returncode == 0:
            print(json.dumps({"continue": True}))
            return 0
        output = (result.stdout or result.stderr or "Verification failed.").strip()
        print(
            json.dumps(
                {
                    "decision": "block",
                    "reason": (
                        "Final verification failed. Fix issues before finishing."
                        f"\\n\\n{output[:8000]}"
                    ),
                }
            )
        )
        return 0


    if __name__ == "__main__":
        sys.exit(main())
    """
)

PACKAGE_JSON = textwrap.dedent(
    """\
    {
      "name": "ai-guardrails-project",
      "private": true,
      "devDependencies": {
        "@taplo/cli": "0.7.0",
        "markdownlint-cli2": "0.22.1"
      }
    }
    """
)


@dataclass(frozen=True)
class StarterFile:
    """One file generated by the initializer."""

    path: str
    content: str
    tracks: tuple[str, ...]


STARTER_FILES = (
    StarterFile("config/pyproject.guardrails.toml", STARTER_PYPROJECT, TRACKS),
    StarterFile(".pre-commit-config.yaml", PRE_COMMIT_CONFIG, TRACKS),
    StarterFile(".github/workflows/verify.yml", WORKFLOW, TRACKS),
    StarterFile("AGENTS.md", AGENTS, (AGENT_TRACK, HARDENING_TRACK)),
    StarterFile(".codex/config.toml", CODEX_CONFIG, (AGENT_TRACK, HARDENING_TRACK)),
    StarterFile(
        ".codex/hooks/post_edit_fast_gate.py",
        POST_EDIT_HOOK,
        (AGENT_TRACK, HARDENING_TRACK),
    ),
    StarterFile(".codex/hooks/stop_full_verify.py", STOP_HOOK, (AGENT_TRACK, HARDENING_TRACK)),
    StarterFile("package.json", PACKAGE_JSON, (HARDENING_TRACK,)),
)
