"""Tests for the standalone file-length helper."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

from ai_guardrails.checks import file_lengths as check_file_lengths


def test_file_length_helpers_find_eligible_python_files(tmp_path: Path) -> None:
    source = tmp_path / "pkg"
    source.mkdir()
    kept = source / "kept.py"
    generated = source / "generated.py"
    kept.write_text("x = 1\n\n# comment\ny = 2\n", encoding="utf-8")
    generated.write_text("# Generated by tool\nx = 1\n", encoding="utf-8")

    expanded = check_file_lengths.expand_paths([str(source)], changed_only=False)
    eligible = check_file_lengths.eligible_python_paths(expanded, include_generated=False)

    assert check_file_lengths.count_lines(kept) == (4, 2)
    assert kept in eligible
    assert generated not in eligible
    assert check_file_lengths.length_failures([kept], max_physical=3, max_source=10)


def test_file_length_changed_only_uses_git_files(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(check_file_lengths, "git_files", lambda command: [Path("changed.py")])

    assert check_file_lengths.expand_paths([], changed_only=True) == [Path("changed.py")]


def test_file_length_git_files_handles_success_and_failure(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    completed = subprocess.CompletedProcess(["git"], 0, stdout="a.py\nREADME.md\n", stderr="")
    monkeypatch.setattr(check_file_lengths.subprocess, "run", lambda *args, **_kwargs: completed)

    assert check_file_lengths.git_files(["git"]) == [Path("a.py")]

    def fail_run(*args: object, **_kwargs: object) -> subprocess.CompletedProcess[str]:
        raise subprocess.CalledProcessError(1, ["git"])

    monkeypatch.setattr(check_file_lengths.subprocess, "run", fail_run)
    assert check_file_lengths.git_files(["git"]) == []


def test_file_length_main_reports_failures(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.chdir(tmp_path)
    target = tmp_path / "long.py"
    target.write_text("a = 1\nb = 2\n", encoding="utf-8")

    assert check_file_lengths.main([str(target), "--max-physical", "1"]) == 1
    assert "File length check failed" in capsys.readouterr().out


def test_file_length_baseline_allows_clean_legacy_violation(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(tmp_path)
    target = tmp_path / "legacy.py"
    baseline = tmp_path / "file-length-baseline.json"
    target.write_text("a = 1\nb = 2\nc = 3\n", encoding="utf-8")
    baseline.write_text(
        json.dumps(
            {
                "version": 1,
                "limits": {"max_physical": 1, "max_source": 1},
                "files": {"legacy.py": {"physical": 3, "source": 3}},
            }
        ),
        encoding="utf-8",
    )

    result = check_file_lengths.main(
        ["legacy.py", "--max-physical", "1", "--baseline", str(baseline)]
    )

    assert result == 0


def test_file_length_baseline_fails_worsened_legacy_violation(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.chdir(tmp_path)
    target = tmp_path / "legacy.py"
    baseline = tmp_path / "file-length-baseline.json"
    target.write_text("a = 1\nb = 2\nc = 3\n", encoding="utf-8")
    baseline.write_text(
        json.dumps(
            {
                "version": 1,
                "limits": {"max_physical": 1, "max_source": 1},
                "files": {"legacy.py": {"physical": 2, "source": 2}},
            }
        ),
        encoding="utf-8",
    )

    result = check_file_lengths.main(
        ["legacy.py", "--max-physical", "1", "--baseline", str(baseline)]
    )

    assert result == 1
    assert "worsened legacy file" in capsys.readouterr().out


def test_file_length_baseline_fails_new_oversized_file(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.chdir(tmp_path)
    target = tmp_path / "new.py"
    baseline = tmp_path / "file-length-baseline.json"
    target.write_text("a = 1\nb = 2\n", encoding="utf-8")
    baseline.write_text(
        json.dumps(
            {
                "version": 1,
                "limits": {"max_physical": 1, "max_source": 1},
                "files": {},
            }
        ),
        encoding="utf-8",
    )

    result = check_file_lengths.main(["new.py", "--max-physical", "1", "--baseline", str(baseline)])

    assert result == 1
    assert "new oversized file" in capsys.readouterr().out


def test_file_length_can_write_baseline(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.chdir(tmp_path)
    target = tmp_path / "legacy.py"
    baseline = tmp_path / "file-length-baseline.json"
    target.write_text("a = 1\nb = 2\n", encoding="utf-8")

    result = check_file_lengths.main(
        ["legacy.py", "--max-physical", "1", "--write-baseline", str(baseline)]
    )

    assert result == 0
    payload = json.loads(baseline.read_text(encoding="utf-8"))
    assert payload["files"] == {"legacy.py": {"physical": 2, "source": 2}}
