"""Tests for standalone helper scripts and guardrail entrypoint."""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from scripts import (
    check_change_budget,
    check_file_lengths,
    check_suppression_budget,
    check_tach_config,
    guardrail,
    guardrail_tach,
)
from scripts.guardrail_config import GuardrailConfig

BOOTSTRAP_STATUS = 11
DOCTOR_STATUS = 14
INSTALL_STATUS = 12
VERIFY_STATUS = 13
GUIDANCE_STATUS = 15
UNKNOWN_COMMAND_STATUS = 2
DEPENDENCY_FAILURE_STATUS = 7
NOQA_SUPPRESSION = "# " + "noqa"
TYPE_IGNORE_SUPPRESSION = "# " + "type: ignore[assignment]"


def test_file_length_helpers_find_eligible_python_files(tmp_path: Path) -> None:
    source = tmp_path / "pkg"
    source.mkdir()
    kept = source / "kept.py"
    generated = source / "generated.py"
    kept.write_text("x = 1\n\n# comment\ny = 2\n", encoding="utf-8")
    generated.write_text("# Generated by tool\nx = 1\n", encoding="utf-8")

    expanded = check_file_lengths.expand_paths([str(source)], changed_only=False)
    eligible = check_file_lengths.eligible_python_paths(expanded, include_generated=False)

    assert check_file_lengths.count_lines(kept) == (4, 2)
    assert kept in eligible
    assert generated not in eligible
    assert check_file_lengths.length_failures([kept], max_physical=3, max_source=10)


def test_file_length_changed_only_uses_git_files(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(check_file_lengths, "git_files", lambda command: [Path("changed.py")])

    assert check_file_lengths.expand_paths([], changed_only=True) == [Path("changed.py")]


def test_file_length_git_files_handles_success_and_failure(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    completed = subprocess.CompletedProcess(["git"], 0, stdout="a.py\nREADME.md\n", stderr="")
    monkeypatch.setattr(check_file_lengths.subprocess, "run", lambda *args, **_kwargs: completed)

    assert check_file_lengths.git_files(["git"]) == [Path("a.py")]

    def fail_run(*args: object, **_kwargs: object) -> subprocess.CompletedProcess[str]:
        raise subprocess.CalledProcessError(1, ["git"])

    monkeypatch.setattr(check_file_lengths.subprocess, "run", fail_run)
    assert check_file_lengths.git_files(["git"]) == []


def test_file_length_main_reports_failures(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.chdir(tmp_path)
    target = tmp_path / "long.py"
    target.write_text("a = 1\nb = 2\n", encoding="utf-8")

    assert check_file_lengths.main([str(target), "--max-physical", "1"]) == 1
    assert "File length check failed" in capsys.readouterr().out


def test_change_budget_classifies_python_source_and_tests() -> None:
    config = GuardrailConfig(source_roots=("scripts",), test_roots=("tests",))
    changes = [
        check_change_budget.FileChange("scripts/tool.py", 2, 1),
        check_change_budget.FileChange("tests/test_tool.py", 1, 0),
        check_change_budget.FileChange("README.md", 4, 0),
    ]

    source, tests = check_change_budget.changed_python_files(changes, config)

    assert [change.path for change in source] == ["scripts/tool.py"]
    assert [change.path for change in tests] == ["tests/test_tool.py"]
    assert check_change_budget.should_exclude("poetry.lock")
    assert check_change_budget.diff_target_label("HEAD", staged=True) == "staged changes"


def test_change_budget_reports_missing_tests_when_required() -> None:
    args = check_change_budget.parse_args([])
    config = GuardrailConfig(source_roots=("scripts",), test_roots=("tests",), require_tests=True)

    failures, warnings = check_change_budget.budget_messages(
        args,
        config,
        [check_change_budget.FileChange("scripts/tool.py", 1, 0)],
        [],
    )

    assert failures == []
    assert warnings == ["Python source changed, but no configured Python test files changed."]


def test_run_git_numstat_parses_output(monkeypatch: pytest.MonkeyPatch) -> None:
    completed = subprocess.CompletedProcess(
        ["git"],
        0,
        stdout="2\t3\tscripts/tool.py\n-\t-\timage.png\n",
        stderr="",
    )
    monkeypatch.setattr(check_change_budget.subprocess, "run", lambda *args, **_kwargs: completed)

    changes = check_change_budget.run_git_numstat("HEAD", staged=False)

    assert changes == [check_change_budget.FileChange("scripts/tool.py", 2, 3)]


def test_change_budget_limit_helpers_report_warnings_and_blocks() -> None:
    args = check_change_budget.parse_args(
        ["--warn-lines", "1", "--block-lines", "3", "--warn-files", "1", "--block-files", "2"]
    )
    config = GuardrailConfig()
    changes = [
        check_change_budget.FileChange("scripts/a.py", 2, 0),
        check_change_budget.FileChange("scripts/b.py", 2, 0),
        check_change_budget.FileChange("scripts/c.py", 1, 0),
    ]
    warnings: list[str] = []

    line_failures = check_change_budget.line_budget_failures(args, config, changes, warnings)
    file_failures = check_change_budget.file_budget_failures(args, config, changes, warnings)

    assert line_failures == ["Python source diff is too large: 5 changed lines (block limit: 3)."]
    assert file_failures == ["Too many Python source files touched: 3 (block limit: 2)."]


def test_change_budget_main_handles_runtime_error(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    def fail_run(base_ref: str, *, staged: bool) -> list[check_change_budget.FileChange]:
        raise RuntimeError("git failed")

    monkeypatch.setattr(check_change_budget, "run_git_numstat", fail_run)

    assert check_change_budget.main([]) == 1
    assert "git failed" in capsys.readouterr().out


def test_change_budget_main_can_fail_warnings_as_errors(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.setattr(
        check_change_budget,
        "run_git_numstat",
        lambda base_ref, staged=False: [
            check_change_budget.FileChange("src/app.py", 1, 0),
        ],
    )
    monkeypatch.setattr(
        check_change_budget,
        "load_config",
        lambda: GuardrailConfig(source_roots=("src",), test_roots=("tests",), require_tests=True),
    )

    assert check_change_budget.main(["--warnings-as-errors"]) == 1
    assert "Change budget warnings" in capsys.readouterr().out


def test_change_budget_can_allow_source_changes_without_test_changes() -> None:
    args = check_change_budget.parse_args(["--allow-source-without-test-change"])
    config = GuardrailConfig(source_roots=("scripts",), test_roots=("tests",), require_tests=True)

    failures, warnings = check_change_budget.budget_messages(
        args,
        config,
        [check_change_budget.FileChange("scripts/tool.py", 1, 0)],
        [],
    )

    assert failures == []
    assert warnings == []


def test_justfile_full_output_recipe_uses_repo_roots() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    justfile = (repo_root / "justfile").read_text(encoding="utf-8")
    recipe = justfile.split("verify-full-output:", maxsplit=1)[1].split(
        "clean-verify-logs:",
        maxsplit=1,
    )[0]

    assert " --cov=src" not in recipe
    assert "radon cc src" not in recipe
    assert "pylint src" not in recipe
    assert "bandit -q -r src" not in recipe


def test_suppression_budget_detects_broad_suppressions() -> None:
    added = [
        ("scripts/tool.py", f"value = call()  {NOQA_SUPPRESSION}"),
        ("scripts/tool.py", f"other = call()  {TYPE_IGNORE_SUPPRESSION}"),
    ]

    failures = check_suppression_budget.suppression_failures(added, max_new_suppressions=1)

    assert any("broad noqa" in failure for failure in failures)
    assert any("Too many new suppression comments" in failure for failure in failures)


def test_suppression_added_python_lines_parses_diff(monkeypatch: pytest.MonkeyPatch) -> None:
    diff = f"+++ b/scripts/tool.py\n+value = call()  {NOQA_SUPPRESSION}\n context\n"
    completed = subprocess.CompletedProcess(["git"], 0, stdout=diff, stderr="")
    monkeypatch.setattr(
        check_suppression_budget.subprocess,
        "run",
        lambda *args, **_kwargs: completed,
    )

    assert check_suppression_budget.added_python_lines("HEAD", staged=False) == [
        ("scripts/tool.py", f"value = call()  {NOQA_SUPPRESSION}")
    ]


def test_suppression_main_handles_runtime_error(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    def fail_added(base_ref: str, *, staged: bool) -> list[tuple[str, str]]:
        raise RuntimeError("diff failed")

    monkeypatch.setattr(check_suppression_budget, "added_python_lines", fail_added)

    assert check_suppression_budget.main([]) == 1
    assert "diff failed" in capsys.readouterr().out


def test_tach_config_issues_require_modules_and_strict_root(tmp_path: Path) -> None:
    (tmp_path / "tach.toml").write_text(
        """
source_roots = ["."]
root_module = "ignore"
""".strip(),
        encoding="utf-8",
    )

    issues = guardrail_tach.tach_config_issues(tmp_path, require_strict_root=True)

    assert "tach.toml must define at least one module" in issues
    assert 'tach.toml must set root_module = "forbid"' in issues


def test_tach_config_main_reports_success(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.chdir(tmp_path)
    (tmp_path / "tach.toml").write_text(
        """
source_roots = ["."]
root_module = "forbid"

[[modules]]
path = "scripts"
""".strip(),
        encoding="utf-8",
    )

    assert check_tach_config.main([]) == 0
    assert "tach.toml is configured" in capsys.readouterr().out


def test_guardrail_main_routes_commands(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(guardrail, "bootstrap", lambda: BOOTSTRAP_STATUS)
    monkeypatch.setattr(guardrail, "doctor_main", lambda args: DOCTOR_STATUS)
    monkeypatch.setattr(guardrail, "guidance_main", lambda args: GUIDANCE_STATUS)
    monkeypatch.setattr(guardrail, "install", lambda: INSTALL_STATUS)
    monkeypatch.setattr(guardrail, "verify_main", lambda args: VERIFY_STATUS)

    assert guardrail.main(["bootstrap"]) == BOOTSTRAP_STATUS
    assert guardrail.main(["doctor", "--strict"]) == DOCTOR_STATUS
    assert guardrail.main(["guidance", "--check"]) == GUIDANCE_STATUS
    assert guardrail.main(["install"]) == INSTALL_STATUS
    assert guardrail.main(["verify", "--profile", "fast"]) == VERIFY_STATUS
    assert guardrail.main(["unknown"]) == UNKNOWN_COMMAND_STATUS


def test_guardrail_file_entrypoint_help_remains_supported() -> None:
    repo_root = Path(__file__).resolve().parents[1]

    result = subprocess.run(  # nosec B603
        ["python3", "scripts/guardrail.py", "--help"],
        cwd=repo_root,
        text=True,
        capture_output=True,
        check=False,
    )

    assert result.returncode == 0
    assert "python -m scripts.guardrail doctor" in result.stdout


def test_guardrail_install_helpers(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    assert guardrail.install_pre_commit(tmp_path) == 0

    (tmp_path / ".pre-commit-config.yaml").write_text("repos: []\n", encoding="utf-8")
    monkeypatch.setattr(guardrail, "find_pre_commit", lambda repo_root: None)
    assert guardrail.install_pre_commit(tmp_path) == 1

    dependency_file = tmp_path / "config" / "dev-dependencies.txt"
    dependency_file.parent.mkdir()
    dependency_file.write_text("pytest\n", encoding="utf-8")
    python_path = tmp_path / ".venv" / "bin" / "python"
    python_path.parent.mkdir(parents=True)
    python_path.write_text("", encoding="utf-8")

    calls: list[list[str]] = []

    def fake_run(command: list[str], **_kwargs: object) -> subprocess.CompletedProcess[str]:
        calls.append(command)
        return subprocess.CompletedProcess(command, 0, "", "")

    monkeypatch.setattr(guardrail.subprocess, "run", fake_run)
    assert guardrail.install_dependencies(tmp_path, python_path) == 0
    assert calls[0][-2:] == ["-r", "config/dev-dependencies.txt"]

    (tmp_path / "config" / "dev-lock.txt").write_text("pytest==9.1.1\n", encoding="utf-8")
    calls.clear()
    assert guardrail.install_dependencies(tmp_path, python_path) == 0
    assert calls[0][-2:] == ["-r", "config/dev-lock.txt"]


def test_guardrail_bootstrap_and_virtualenv_helpers(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    python_path = tmp_path / ".venv" / "bin" / "python"
    monkeypatch.setattr(guardrail.shutil, "which", lambda name: "/usr/bin/python3")

    def fake_run(command: list[str], **_kwargs: object) -> subprocess.CompletedProcess[str]:
        python_path.parent.mkdir(parents=True)
        python_path.write_text("", encoding="utf-8")
        return subprocess.CompletedProcess(command, 0, "", "")

    monkeypatch.setattr(guardrail.subprocess, "run", fake_run)

    assert guardrail.ensure_virtualenv(tmp_path) == python_path

    monkeypatch.setattr(guardrail, "ensure_virtualenv", lambda repo_root: python_path)
    monkeypatch.setattr(guardrail, "install_dependencies", lambda repo_root, path: 0)
    monkeypatch.setattr(guardrail, "install", lambda: 0)
    assert guardrail.bootstrap() == 0


def test_guardrail_bootstrap_failure_branches(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(guardrail, "ensure_virtualenv", lambda repo_root: None)
    assert guardrail.bootstrap() == 1

    python_path = tmp_path / ".venv" / "bin" / "python"
    monkeypatch.setattr(guardrail, "ensure_virtualenv", lambda repo_root: python_path)
    monkeypatch.setattr(
        guardrail,
        "install_dependencies",
        lambda repo_root, path: DEPENDENCY_FAILURE_STATUS,
    )
    assert guardrail.bootstrap() == DEPENDENCY_FAILURE_STATUS


def test_guardrail_virtualenv_failure_branches(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    existing = tmp_path / ".venv" / "bin" / "python"
    existing.parent.mkdir(parents=True)
    existing.write_text("", encoding="utf-8")
    assert guardrail.ensure_virtualenv(tmp_path) == existing

    missing_python_root = tmp_path / "missing-python"
    monkeypatch.setattr(guardrail.shutil, "which", lambda name: None)
    assert guardrail.ensure_virtualenv(missing_python_root) is None
    assert "python3 command not found" in capsys.readouterr().err

    failed_venv_root = tmp_path / "failed-venv"
    monkeypatch.setattr(guardrail.shutil, "which", lambda name: "/usr/bin/python3")
    monkeypatch.setattr(
        guardrail.subprocess,
        "run",
        lambda command, **_kwargs: subprocess.CompletedProcess(command, 1, "", ""),
    )
    assert guardrail.ensure_virtualenv(failed_venv_root) is None


def test_guardrail_dependency_install_requires_manifest(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    python_path = tmp_path / ".venv" / "bin" / "python"

    assert guardrail.install_dependencies(tmp_path, python_path) == 1
    assert "dev-lock.txt or config/dev-dependencies.txt" in capsys.readouterr().err


def test_guardrail_reports_codex_hooks(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    config_path = tmp_path / ".codex" / "config.toml"
    config_path.parent.mkdir()
    config_path.write_text("[features]\nhooks = true\n", encoding="utf-8")

    guardrail.report_codex_hooks(tmp_path)

    assert "Codex hooks are configured" in capsys.readouterr().out
