"""Phase 10 branch and error-path coverage tests."""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from scripts import (
    check_change_budget,
    check_file_lengths,
    check_suppression_budget,
    check_tach_config,
    guardrail_executor,
)
from scripts.guardrail_config import GuardrailConfig
from scripts.guardrail_models import Check

PYLINT_DISABLE_ALL = "# pylint:" + " disable" + "=all"
PYRIGHT_REPORT_DISABLE = "# py" + "right: reportGeneralTypeIssues" + "=false"


def test_change_budget_numstat_failure_includes_target(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def fail_run(*args: object, **kwargs: object) -> subprocess.CompletedProcess[str]:
        raise subprocess.CalledProcessError(1, ["git"], stderr="bad ref")

    monkeypatch.setattr(check_change_budget.subprocess, "run", fail_run)

    with pytest.raises(RuntimeError, match="staged changes: bad ref"):
        check_change_budget.run_git_numstat("HEAD", staged=True)


def test_change_budget_numstat_skips_binary_excluded_and_malformed_rows(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    completed = subprocess.CompletedProcess(
        ["git"],
        0,
        stdout=(
            "malformed\n-\t-\tscripts/binary.py\n1\t1\tpackage-lock.json\n2\t3\tscripts/app.py\n"
        ),
        stderr="",
    )
    monkeypatch.setattr(check_change_budget.subprocess, "run", lambda *args, **kwargs: completed)

    assert check_change_budget.run_git_numstat("HEAD", staged=False) == [
        check_change_budget.FileChange("scripts/app.py", 2, 3)
    ]


def test_suppression_diff_failure_includes_target(monkeypatch: pytest.MonkeyPatch) -> None:
    def fail_run(*args: object, **kwargs: object) -> subprocess.CompletedProcess[str]:
        raise subprocess.CalledProcessError(1, ["git"], stderr="diff failed")

    monkeypatch.setattr(check_suppression_budget.subprocess, "run", fail_run)

    with pytest.raises(RuntimeError, match="'origin/main': diff failed"):
        check_suppression_budget.added_python_lines("origin/main", staged=False)


def test_suppression_classifier_covers_specific_broad_patterns() -> None:
    issues = [
        *check_suppression_budget.classify("pkg/a.py", f"value = call() {PYLINT_DISABLE_ALL}"),
        *check_suppression_budget.classify("pkg/b.py", PYRIGHT_REPORT_DISABLE),
    ]

    assert [issue.reason for issue in issues] == [
        "pylint disable=all",
        "file-level pyright diagnostic disable",
    ]
    assert check_suppression_budget.classify("pkg/c.py", "value = call()") == []


def test_suppression_main_reports_runtime_error(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    def fail_added(base_ref: str, *, staged: bool) -> list[tuple[str, str]]:
        raise RuntimeError("git unavailable")

    monkeypatch.setattr(check_suppression_budget, "added_python_lines", fail_added)

    assert check_suppression_budget.main([]) == 1
    assert "git unavailable" in capsys.readouterr().out


def test_file_length_generated_detection_treats_read_errors_as_not_generated(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    target = tmp_path / "broken.py"
    target.write_text("# generated by tool\n", encoding="utf-8")

    monkeypatch.setattr(Path, "read_text", lambda self, **kwargs: (_ for _ in ()).throw(OSError))

    assert check_file_lengths.is_generated(target) is False


def test_file_length_expand_paths_falls_back_to_configured_roots(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(tmp_path)
    source = tmp_path / "pkg"
    source.mkdir()
    target = source / "app.py"
    target.write_text("x = 1\n", encoding="utf-8")
    monkeypatch.setattr(check_file_lengths, "git_files", lambda command: [])
    monkeypatch.setattr(
        check_file_lengths,
        "load_config",
        lambda: GuardrailConfig(file_length_paths=("pkg",)),
    )

    assert check_file_lengths.expand_paths([], changed_only=False) == [Path("pkg/app.py")]


def test_tach_config_main_reports_issues(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.setattr(check_tach_config, "tach_config_issues", lambda *args, **kwargs: ["bad"])

    assert check_tach_config.main(["--strict-root-module"]) == 1
    assert "bad" in capsys.readouterr().out


def test_executor_run_check_reports_oserror(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    def fail_run(command: list[str]) -> tuple[int, str]:
        raise OSError("missing executable")

    monkeypatch.setattr(guardrail_executor, "run_command", fail_run)

    result = guardrail_executor.run_check(
        Check("tool", ["missing"], frozenset()),
        tmp_path / "logs",
        max_lines=5,
        max_chars=500,
    )

    assert result.passed is False
    assert "missing executable" in result.output
    assert (tmp_path / "logs" / "tool.log").exists()
