"""Python file classification helpers."""

from __future__ import annotations

from pathlib import Path

from agent_maintainer.config.schema import MaintainerConfig
from agent_maintainer.core.config import path_matches_roots
from agent_maintainer.ecosystems.models import FileClassification, FileRole

ECOSYSTEM_NAME = "python"

IGNORED_PARTS = frozenset(
    (
        ".git",
        ".hg",
        ".svn",
        ".venv",
        "venv",
        "env",
        "__pycache__",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".tox",
        "build",
        "dist",
        "node_modules",
    ),
)

GENERATED_MARKERS = (
    "@generated",
    "generated by",
    "automatically generated",
    "do not edit",
)
DOC_EXTENSIONS = frozenset((".md", ".rst", ".txt"))
CONFIG_NAMES = frozenset(
    (
        "pyproject.toml",
        "tox.ini",
        "setup.cfg",
        "mypy.ini",
        "ruff.toml",
        ".pre-commit-config.yaml",
    ),
)
CONFIG_EXTENSIONS = frozenset((".toml", ".yaml", ".yml", ".json", ".ini"))
DEPENDENCY_NAMES = frozenset(
    (
        "requirements.txt",
        "requirements-dev.txt",
        "dev-requirements.txt",
        "constraints.txt",
        "poetry.lock",
        "uv.lock",
        "pdm.lock",
    ),
)


def classify_path(
    path: str | Path,
    config: MaintainerConfig,
    *,
    repo_root: Path | None = None,
) -> FileClassification | None:
    """Classify one path for the Python ecosystem."""
    original = Path(path)
    normalized = _normalize_path(original)

    repo_classification = _classify_repo_file(original, normalized)
    if repo_classification is not None:
        return repo_classification

    if original.suffix != ".py":
        return None
    return _classify_python_file(
        original,
        normalized,
        config,
        repo_root=repo_root,
    )


def _classify_repo_file(
    path: Path,
    normalized: str,
) -> FileClassification | None:
    """Classify ignored or repo-adjacent non-source files."""
    if _is_ignored(path):
        return FileClassification(
            normalized,
            ECOSYSTEM_NAME,
            FileRole.IGNORED,
            ignored=True,
            reason="ignored tool cache path",
        )
    if path.name in DEPENDENCY_NAMES:
        return FileClassification(
            normalized,
            ECOSYSTEM_NAME,
            FileRole.DEPENDENCY,
            reason="python dependency file",
        )
    if path.name in CONFIG_NAMES or path.suffix in CONFIG_EXTENSIONS:
        return FileClassification(
            normalized,
            ECOSYSTEM_NAME,
            FileRole.CONFIG,
            reason="configuration file",
        )
    if path.suffix in DOC_EXTENSIONS:
        return FileClassification(
            normalized,
            ECOSYSTEM_NAME,
            FileRole.DOCS,
            reason="documentation file",
        )
    return None


def _classify_python_file(
    path: Path,
    normalized: str,
    config: MaintainerConfig,
    *,
    repo_root: Path | None,
) -> FileClassification:
    """Classify one Python file after generic repo-file checks."""
    if _is_generated(path, repo_root=repo_root):
        return FileClassification(
            normalized,
            ECOSYSTEM_NAME,
            FileRole.GENERATED,
            generated=True,
            reason="python generated file marker",
        )
    if path_matches_roots(normalized, config.test_roots):
        return FileClassification(
            normalized,
            ECOSYSTEM_NAME,
            FileRole.TEST,
            reason="matches configured test roots",
        )
    if path_matches_roots(normalized, config.source_roots):
        return FileClassification(
            normalized,
            ECOSYSTEM_NAME,
            FileRole.SOURCE,
            reason="matches configured source roots",
        )
    return FileClassification(
        normalized,
        ECOSYSTEM_NAME,
        FileRole.UNKNOWN,
        reason="python file outside configured roots",
    )


def _normalize_path(path: Path) -> str:
    """Return a repository-style path string."""
    return path.as_posix().lstrip("./")


def _is_ignored(path: Path) -> bool:
    """Return whether path lives under an ignored tool/cache directory."""
    return any(part in IGNORED_PARTS for part in path.parts)


def _is_generated(path: Path, *, repo_root: Path | None) -> bool:
    """Return whether a Python file advertises generated status near the top."""
    read_path = path if repo_root is None or path.is_absolute() else repo_root / path
    try:
        head = "\n".join(
            read_path.read_text(encoding="utf-8", errors="replace").splitlines()[:10],
        )
    except OSError:
        return False
    lowered = head.lower()
    return any(marker in lowered for marker in GENERATED_MARKERS)
