"""Fail when Python files exceed repository size limits.

Default behavior:
- If explicit paths are passed, check those paths.
- Otherwise, check tracked Python files when Git is available.
- Otherwise, fall back to scanning configured file_length_paths.

The check reports only oversized files and exits nonzero when any file violates
limits. Generated files are skipped when they contain common generated-file
markers near the top.
"""

from __future__ import annotations

import argparse
import json
import subprocess  # nosec B404
import sys
from pathlib import Path

from agent_maintainer.core.config import load_config

EXCLUDED_DIRS = frozenset(
    (
        ".git",
        ".hg",
        ".svn",
        ".venv",
        "venv",
        "env",
        "__pycache__",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".tox",
        "build",
        "dist",
        "node_modules",
    )
)

GENERATED_MARKERS = (
    "@generated",
    "generated by",
    "automatically generated",
    "do not edit",
)


def parse_args(argv: list[str]) -> argparse.Namespace:
    """Parse file-length command-line options."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("paths", nargs="*", help="Specific files or directories to check.")
    parser.add_argument(
        "--root", action="append", help="Default scan root. May be repeated or comma-separated."
    )
    parser.add_argument("--max-physical", type=int)
    parser.add_argument("--max-source", type=int)
    parser.add_argument(
        "--changed-only",
        action="store_true",
        help="Check Python files changed relative to HEAD.",
    )
    parser.add_argument(
        "--include-generated",
        action="store_true",
        help="Do not skip files marked as generated.",
    )
    parser.add_argument(
        "--baseline",
        help="JSON baseline for legacy-ratchet oversized files.",
    )
    parser.add_argument(
        "--write-baseline",
        help="Write a JSON baseline of current oversized files and exit.",
    )
    return parser.parse_args(argv)


def is_excluded(path: Path) -> bool:
    """Return whether a path lives under an ignored tool/cache directory."""

    return any(part in EXCLUDED_DIRS for part in path.parts)


def is_generated(path: Path) -> bool:
    """Return whether a file advertises itself as generated near the top."""

    try:
        head = "\n".join(path.read_text(encoding="utf-8", errors="replace").splitlines()[:10])
    except OSError:
        return False
    lowered = head.lower()
    return any(marker in lowered for marker in GENERATED_MARKERS)


def git_files(command: list[str]) -> list[Path]:
    """Return Python paths from a git command, or an empty list on failure."""

    try:
        result = subprocess.run(  # nosec B603
            command,
            text=True,
            capture_output=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return []

    return [Path(line) for line in result.stdout.splitlines() if line.endswith(".py")]


def parse_csv_like(values: list[str] | None) -> list[str]:
    """Normalize repeated comma-separated path options."""

    if not values:
        return []
    items: list[str] = []
    for value in values:
        items.extend(part.strip() for part in value.split(","))
    return [item.rstrip("/") or "." for item in items if item]


def expand_paths(paths: list[str], changed_only: bool) -> list[Path]:
    """Resolve explicit, changed-only, tracked, or configured scan targets."""

    if changed_only:
        return changed_python_paths()

    if paths:
        return expand_explicit_paths(paths)

    tracked = git_files(["git", "ls-files", "*.py"])
    if tracked:
        return tracked

    return configured_file_length_paths()


def changed_python_paths() -> list[Path]:
    """Return Python files changed against HEAD."""

    return git_files(["git", "diff", "--name-only", "HEAD", "--", "*.py"])


def expand_explicit_paths(paths: list[str]) -> list[Path]:
    """Expand explicit file and directory arguments into Python files."""

    expanded: list[Path] = []
    for raw in paths:
        path = Path(raw)
        if path.is_dir():
            expanded.extend(path.rglob("*.py"))
        elif path.suffix == ".py":
            expanded.append(path)
    return expanded


def configured_file_length_paths() -> list[Path]:
    """Expand configured fallback roots into Python files."""

    expanded: list[Path] = []
    for root_raw in load_config().file_length_paths:
        root = Path(root_raw)
        if root.exists():
            expanded.extend(root.rglob("*.py"))
    return expanded


def count_lines(path: Path) -> tuple[int, int]:
    """Return physical and source-line counts for one Python file."""

    physical = 0
    source = 0

    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        physical += 1
        stripped = line.strip()

        if not stripped:
            continue
        if stripped.startswith("#"):
            continue

        source += 1

    return physical, source


def eligible_python_paths(paths: list[Path], include_generated: bool) -> list[Path]:
    """Deduplicate paths and filter to checkable Python files."""

    eligible: list[Path] = []
    seen: set[Path] = set()
    for path in paths:
        path = path.resolve() if path.is_absolute() else path
        if path in seen:
            continue
        seen.add(path)

        if not path.exists() or path.suffix != ".py" or is_excluded(path):
            continue
        if not include_generated and is_generated(path):
            continue

        eligible.append(path)
    return eligible


def length_failures(paths: list[Path], max_physical: int, max_source: int) -> list[str]:
    """Return file-length failures for eligible Python files."""

    failures: list[str] = []
    for path in paths:
        physical, source = count_lines(path)
        if physical > max_physical or source > max_source:
            failures.append(
                f"{path}: {physical} physical lines, {source} source lines "
                f"(limits: {max_physical} physical, {max_source} source)"
            )
    return failures


def baseline_key(path: Path) -> str:
    """Return the stable repository-relative baseline key for a path."""

    try:
        candidate = path.resolve().relative_to(Path.cwd().resolve())
    except ValueError:
        candidate = path
    return candidate.as_posix()


def read_baseline(path: Path) -> dict[str, tuple[int, int]]:
    """Read a file-length baseline as path keys mapped to physical/source counts."""

    if not path.exists():
        return {}
    payload = json.loads(path.read_text(encoding="utf-8"))
    files = payload.get("files", {})
    if not isinstance(files, dict):
        raise ValueError("file-length baseline 'files' must be an object")
    baseline: dict[str, tuple[int, int]] = {}
    for file_path, raw_counts in files.items():
        if not isinstance(raw_counts, dict):
            raise ValueError(f"file-length baseline record for {file_path!r} must be an object")
        baseline[str(file_path)] = (
            int(raw_counts.get("physical", 0)),
            int(raw_counts.get("source", 0)),
        )
    return baseline


def baseline_records(
    paths: list[Path], max_physical: int, max_source: int
) -> dict[str, dict[str, int]]:
    """Return baseline records for files currently above configured limits."""

    records: dict[str, dict[str, int]] = {}
    for path in paths:
        physical, source = count_lines(path)
        if physical > max_physical or source > max_source:
            records[baseline_key(path)] = {"physical": physical, "source": source}
    return dict(sorted(records.items()))


def write_baseline(path: Path, paths: list[Path], max_physical: int, max_source: int) -> None:
    """Write a JSON baseline for currently oversized files."""

    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "version": 1,
        "limits": {"max_physical": max_physical, "max_source": max_source},
        "files": baseline_records(paths, max_physical, max_source),
    }
    path.write_text(f"{json.dumps(payload, indent=2, sort_keys=True)}\n", encoding="utf-8")


def ratchet_length_failures(
    paths: list[Path],
    max_physical: int,
    max_source: int,
    baseline_path: Path,
) -> list[str]:
    """Return only new or worsened file-length failures against a baseline."""

    baseline = read_baseline(baseline_path)
    failures: list[str] = []
    for path in paths:
        physical, source = count_lines(path)
        if physical <= max_physical and source <= max_source:
            continue
        path_key = baseline_key(path)
        previous = baseline.get(path_key)
        if previous is None:
            failures.append(
                f"{path_key}: new oversized file has {physical} physical lines, "
                f"{source} source lines (limits: {max_physical} physical, {max_source} source)"
            )
        elif physical > previous[0] or source > previous[1]:
            failures.append(
                f"{path_key}: worsened legacy file has {physical} physical lines, "
                f"{source} source lines (baseline: {previous[0]} physical, {previous[1]} source)"
            )
    return failures


def print_failures(failures: list[str]) -> None:
    """Print file-length failures with a refactoring-oriented hint."""

    print("File length check failed:\n")
    for failure in failures:
        print(f"  {failure}")
    print("\nSplit oversized files by responsibility instead of suppressing this check.")


def main(argv: list[str]) -> int:
    """Run the file-length check and return a process exit code."""

    args = parse_args(argv)
    config = load_config()
    configured_roots = parse_csv_like(args.root)
    paths = args.paths or configured_roots
    max_physical = args.max_physical or config.file_length_max_physical
    max_source = args.max_source or config.file_length_max_source
    expanded = expand_paths(paths, args.changed_only)
    eligible = eligible_python_paths(expanded, args.include_generated)
    if args.write_baseline:
        write_baseline(Path(args.write_baseline), eligible, max_physical, max_source)
        return 0
    baseline_path = args.baseline or config.file_length_baseline
    if baseline_path:
        failures = ratchet_length_failures(eligible, max_physical, max_source, Path(baseline_path))
    else:
        failures = length_failures(eligible, max_physical, max_source)

    if failures:
        print_failures(failures)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
