"""Tests for Python ecosystem file classification."""

from __future__ import annotations

from pathlib import Path

from agent_maintainer.core.config import MaintainerConfig
from agent_maintainer.ecosystems.models import FileRole
from agent_maintainer.ecosystems.python.classification import classify_path


def test_python_classifier_preserves_source_and_test_roots() -> None:
    """Python source/test roles follow configured roots."""
    config = MaintainerConfig(
        source_roots=("src", "scripts"),
        test_roots=("tests",),
    )

    source = classify_path("src/pkg/app.py", config)
    script = classify_path("scripts/tool.py", config)
    test = classify_path("tests/test_app.py", config)
    outside = classify_path("docs/demo.py", config)

    assert source is not None
    assert source.role == FileRole.SOURCE
    assert source.reason == "matches configured source roots"
    assert script is not None
    assert script.role == FileRole.SOURCE
    assert test is not None
    assert test.role == FileRole.TEST
    assert outside is not None
    assert outside.role == FileRole.UNKNOWN


def test_python_classifier_identifies_generated_and_ignored_files(
    tmp_path: Path,
) -> None:
    """Generated and ignored files are visible to future policy adapters."""
    config = MaintainerConfig(source_roots=("src",), test_roots=("tests",))
    generated = tmp_path / "src" / "pkg" / "generated.py"
    generated.parent.mkdir(parents=True)
    generated.write_text("# Automatically generated by tool\nx = 1\n", encoding="utf-8")

    generated_result = classify_path(
        "src/pkg/generated.py",
        config,
        repo_root=tmp_path,
    )
    ignored_result = classify_path("src/pkg/__pycache__/cached.py", config)

    assert generated_result is not None
    assert generated_result.role == FileRole.GENERATED
    assert generated_result.generated
    assert ignored_result is not None
    assert ignored_result.role == FileRole.IGNORED
    assert ignored_result.ignored


def test_python_classifier_identifies_docs_config_and_dependency_files() -> None:
    """Python provider can classify repo-adjacent non-source files."""
    config = MaintainerConfig()

    pyproject = classify_path("pyproject.toml", config)
    readme = classify_path("README.md", config)
    requirements = classify_path("requirements.txt", config)
    unknown = classify_path("assets/logo.png", config)

    assert pyproject is not None
    assert pyproject.role == FileRole.CONFIG
    assert readme is not None
    assert readme.role == FileRole.DOCS
    assert requirements is not None
    assert requirements.role == FileRole.DEPENDENCY
    assert unknown is None
