"""Static report HTML head and stylesheet rendering."""

from __future__ import annotations

STYLE_LINES = (
    ":root {",
    "  color-scheme: light;",
    "  --bg: #f8fafc;",
    "  --fg: #111827;",
    "  --muted: #4b5563;",
    "  --line: #d1d5db;",
    "  --panel: #ffffff;",
    "  --fail: #b91c1c;",
    "  --warn: #92400e;",
    "  --pass: #047857;",
    "}",
    "body {",
    "  margin: 0;",
    "  background: var(--bg);",
    "  color: var(--fg);",
    '  font: 16px/1.5 system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI",',
    "    sans-serif;",
    "}",
    "a { color: #1d4ed8; }",
    ".hero {",
    "  padding: 32px clamp(20px, 4vw, 56px);",
    "  background: #111827;",
    "  color: #f9fafb;",
    "}",
    ".hero p { color: #d1d5db; margin: 8px 0 0; }",
    ".report {",
    "  max-width: 1120px;",
    "  margin: 0 auto;",
    "  padding: 24px clamp(16px, 3vw, 32px) 48px;",
    "}",
    ".panel {",
    "  background: var(--panel);",
    "  border: 1px solid var(--line);",
    "  border-radius: 8px;",
    "  margin: 16px 0;",
    "  padding: 20px;",
    "}",
    ".grid {",
    "  display: grid;",
    "  gap: 12px;",
    "  grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));",
    "}",
    ".metric { border: 1px solid var(--line); border-radius: 8px; padding: 12px; }",
    ".metric strong { display: block; font-size: 1.45rem; }",
    "table { border-collapse: collapse; width: 100%; }",
    "th,",
    "td {",
    "  border-bottom: 1px solid var(--line);",
    "  padding: 8px;",
    "  text-align: left;",
    "  vertical-align: top;",
    "}",
    "code, pre { background: #f3f4f6; border-radius: 6px; }",
    "code { padding: 1px 4px; }",
    "pre { overflow-x: auto; padding: 12px; }",
    ".status-failed { color: var(--fail); font-weight: 700; }",
    ".status-warning { color: var(--warn); font-weight: 700; }",
    ".status-skipped, [class^='status-skipped-'] { color: var(--muted); font-weight: 700; }",
    ".status-passed { color: var(--pass); font-weight: 700; }",
    "</style>",
    "</head>",
)

HEAD_LINES = (
    "<head>",
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    "<title>Agent Maintainer Verification Report</title>",
    "<style>",
    *STYLE_LINES,
)


def head_html() -> str:
    """Render the static report document head."""
    return "\n".join(HEAD_LINES)
