"""TypeScript and JavaScript file classification helpers."""

from __future__ import annotations

from pathlib import Path

from agent_maintainer.ecosystems.models import FileClassification, FileRole

ECOSYSTEM_NAME = "typescript"

SOURCE_EXTENSIONS = frozenset((".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"))
TEST_NAME_MARKERS = frozenset((".test.", ".spec."))
TEST_PARTS = frozenset(("__tests__", "test", "tests", "spec", "specs"))
IGNORED_PARTS = frozenset(
    (
        ".git",
        ".hg",
        ".svn",
        "node_modules",
        ".next",
        ".nuxt",
        ".svelte-kit",
        ".turbo",
        "coverage",
        "dist",
        "build",
        "out",
    ),
)
GENERATED_PARTS = frozenset(("generated", "__generated__"))
GENERATED_MARKERS = (
    "@generated",
    "generated by",
    "automatically generated",
    "do not edit",
)
CONFIG_NAMES = frozenset(
    (
        "biome.json",
        "biome.jsonc",
        "eslint.config.js",
        "eslint.config.mjs",
        "eslint.config.cjs",
        "jest.config.js",
        "jest.config.ts",
        "next.config.js",
        "next.config.mjs",
        "package.json",
        "prettier.config.js",
        "tsconfig.json",
        "vite.config.js",
        "vite.config.ts",
        "vitest.config.js",
        "vitest.config.ts",
    ),
)
DEPENDENCY_NAMES = frozenset(
    (
        "bun.lockb",
        "package-lock.json",
        "pnpm-lock.yaml",
        "yarn.lock",
    ),
)
DOC_EXTENSIONS = frozenset((".md", ".mdx", ".rst", ".txt"))


def classify_path(path: str | Path) -> FileClassification | None:
    """Classify a path for the experimental TypeScript ecosystem."""
    original = Path(path)
    normalized = _normalize_repo_path(original.as_posix())
    repo_classification = _classify_repo_path(original, normalized)
    if repo_classification is not None:
        return repo_classification
    if original.suffix not in SOURCE_EXTENSIONS:
        return None
    return _classify_source_path(original, normalized)


def _classify_repo_path(path: Path, normalized: str) -> FileClassification | None:
    """Classify repo-adjacent TypeScript ecosystem files."""
    if _has_ignored_part(path):
        return FileClassification(
            normalized,
            ECOSYSTEM_NAME,
            FileRole.IGNORED,
            ignored=True,
            reason="ignored JavaScript tool or build path",
        )
    if path.name in DEPENDENCY_NAMES:
        return FileClassification(
            normalized,
            ECOSYSTEM_NAME,
            FileRole.DEPENDENCY,
            reason="JavaScript dependency lock file",
        )
    if path.name in CONFIG_NAMES:
        return FileClassification(
            normalized,
            ECOSYSTEM_NAME,
            FileRole.CONFIG,
            reason="JavaScript or TypeScript config file",
        )
    if path.suffix in DOC_EXTENSIONS:
        return FileClassification(
            normalized,
            ECOSYSTEM_NAME,
            FileRole.DOCS,
            reason="documentation file",
        )
    return None


def _normalize_repo_path(path: str) -> str:
    """Return repository-relative path text without stripping dot directories."""

    normalized = path.replace("\\", "/")
    while normalized.startswith("./"):
        normalized = normalized[2:]
    return normalized.strip("/")


def _classify_source_path(path: Path, normalized: str) -> FileClassification:
    """Classify TypeScript or JavaScript source-like files."""
    if _looks_generated(path):
        return FileClassification(
            normalized,
            ECOSYSTEM_NAME,
            FileRole.GENERATED,
            generated=True,
            reason="JavaScript or TypeScript generated file marker",
        )
    if _looks_test(path):
        return FileClassification(
            normalized,
            ECOSYSTEM_NAME,
            FileRole.TEST,
            reason="JavaScript or TypeScript test path",
        )
    return FileClassification(
        normalized,
        ECOSYSTEM_NAME,
        FileRole.SOURCE,
        reason="JavaScript or TypeScript source file",
    )


def _has_ignored_part(path: Path) -> bool:
    """Return whether path belongs to a known generated/cache directory."""
    return any(part in IGNORED_PARTS for part in path.parts)


def _looks_test(path: Path) -> bool:
    """Return whether a TypeScript/JavaScript path is test-like."""
    name = path.name
    return any(marker in name for marker in TEST_NAME_MARKERS) or any(
        part in TEST_PARTS for part in path.parts
    )


def _looks_generated(path: Path) -> bool:
    """Return whether a path is generated by name or marker."""
    lower_parts = tuple(part.lower() for part in path.parts)
    lower_name = path.name.lower()
    return any(part in GENERATED_PARTS for part in lower_parts) or any(
        marker in lower_name for marker in GENERATED_MARKERS
    )
