"""Compatibility shim for TypeScript diagnostic parsers."""

from agent_repair_facts.parsers import typescript_diagnostics

TSC_DIAGNOSTIC_RE = typescript_diagnostics.TSC_DIAGNOSTIC_RE
JsonObject = typescript_diagnostics.JsonObject
TypeScriptDiagnostic = typescript_diagnostics.TypeScriptDiagnostic
eslint_message_diagnostic = typescript_diagnostics.eslint_message_diagnostic
eslint_messages = typescript_diagnostics.eslint_messages
eslint_payload_diagnostics = typescript_diagnostics.eslint_payload_diagnostics
eslint_result_diagnostics = typescript_diagnostics.eslint_result_diagnostics
eslint_severity = typescript_diagnostics.eslint_severity
first_failure_line = typescript_diagnostics.first_failure_line
format_diagnostic = typescript_diagnostics.format_diagnostic
jest_assertion_diagnostic = typescript_diagnostics.jest_assertion_diagnostic
jest_failure_message = typescript_diagnostics.jest_failure_message
jest_location = typescript_diagnostics.jest_location
jest_payload_diagnostics = typescript_diagnostics.jest_payload_diagnostics
jest_suite_diagnostics = typescript_diagnostics.jest_suite_diagnostics
jest_test_name = typescript_diagnostics.jest_test_name
optional_int = typescript_diagnostics.optional_int
optional_text = typescript_diagnostics.optional_text
parse_eslint_json = typescript_diagnostics.parse_eslint_json
parse_jest_json = typescript_diagnostics.parse_jest_json
parse_tsc_output = typescript_diagnostics.parse_tsc_output
tsc_diagnostic = typescript_diagnostics.tsc_diagnostic
