"""Starter repository files for package-first initialization."""

from __future__ import annotations

import textwrap
from dataclasses import dataclass

from agent_client_hooks import manifest as hook_manifest
from agent_maintainer.core.scaffold.presets import apply_preset
from agent_maintainer.core.scaffold.template_config import STARTER_PYPROJECT

# docsync:evidence.start evidence.readme.adoption_track_templates
CORE_TRACK = "core"
AGENT_TRACK = "agent"
HARDENING_TRACK = "hardening"
TRACKS = (CORE_TRACK, AGENT_TRACK, HARDENING_TRACK)
AGENT_HOOK_TRACKS = (AGENT_TRACK, HARDENING_TRACK)
CI_ONLY_STARTER_PATHS = frozenset(
    (
        "config/dev-dependencies.txt",
        ".github/workflows/verify.yml",
    )
)

DEV_DEPENDENCIES = "agent-maintainer[core]\n"

PRE_COMMIT_CONFIG = textwrap.dedent(
    """\
    repos:
      - repo: local
        hooks:
          - id: agent-maintainer-fast
            name: Agent Maintainer fast staged checks
            entry: >-
              env AGENT_MAINTAINER_ALLOW_FOREGROUND_WAIT=1
              PYTHONDONTWRITEBYTECODE=1 python3 -m agent_maintainer
              verify --profile fast --base-ref HEAD --staged
            language: system
            pass_filenames: false
            stages: [pre-commit]
          - id: agent-maintainer-affected-tests
            name: Agent Maintainer affected tests
            entry: >-
              env PYTHONDONTWRITEBYTECODE=1 python3 -m agent_maintainer
              test-intel run-changed --base-ref HEAD --staged
            language: system
            pass_filenames: false
            stages: [pre-commit]
          - id: agent-maintainer-prepush
            name: Agent Maintainer complete pre-push checks
            entry: >-
              env AGENT_MAINTAINER_ALLOW_FOREGROUND_WAIT=1
              PYTHONDONTWRITEBYTECODE=1 python3 -m agent_maintainer
              verify --profile precommit --base-ref HEAD
            language: system
            pass_filenames: false
            stages: [pre-push]
    """
)

WORKFLOW = textwrap.dedent(
    """\
    name: verify

    on:
      pull_request:
      push:
        branches: [main]

    permissions:
      contents: read

    jobs:
      verify:
        runs-on: ubuntu-latest
        env:
          PYTHONDONTWRITEBYTECODE: "1"
        steps:
          - name: Checkout
            uses: actions/checkout@v7
            with:
              fetch-depth: 0
              persist-credentials: false
          - name: Set up Python
            uses: actions/setup-python@v6.2.0
            with:
              python-version: "3.11"
          - name: Install project and Agent Maintainer tools
            run: |
              python -m pip install --upgrade pip
              if [ -f config/dev-lock.txt ]; then
                python -m pip install -r config/dev-lock.txt
              fi
              if [ -f config/dev-dependencies.txt ]; then
                python -m pip install -r config/dev-dependencies.txt
              fi
              if [ -f package.json ]; then
                npm ci
              fi
          - name: Verify
            run: |
              BASE_REF="origin/${GITHUB_BASE_REF:-main}"
              python3 -m agent_maintainer verify --profile ci \\
                --base-ref "$BASE_REF" --compare-branch "$BASE_REF"
    """
)

AGENTS = textwrap.dedent(
    """\
    # Repository maintenance

    Read `AGENTS.agent-maintainer.md` before changing code when it exists. That
    file is generated by `python3 -m agent_maintainer guidance` from
    `[tool.agent_maintainer]`.

    Before finishing a code change, run:

    ```bash
    python3 -m agent_maintainer verify --profile precommit
    ```

    For larger changes, run:

    ```bash
    python3 -m agent_maintainer verify --profile full
    ```
    """
)

PACKAGE_JSON = textwrap.dedent(
    """\
    {
      "name": "agent-maintainer-project",
      "private": true,
      "engines": {
        "node": ">=22"
      },
      "devDependencies": {
        "@taplo/cli": "0.7.0",
        "markdownlint-cli2": "0.23.0"
      }
    }
    """
)


@dataclass(frozen=True)
class StarterFile:
    """One initializer file."""

    path: str
    content: str
    tracks: tuple[str, ...]


STARTER_CONFIG_PATH = "config/pyproject.agent-maintainer.toml"

STATIC_STARTER_FILES = (
    StarterFile("config/dev-dependencies.txt", DEV_DEPENDENCIES, TRACKS),
    StarterFile(".pre-commit-config.yaml", PRE_COMMIT_CONFIG, TRACKS),
    StarterFile(".github/workflows/verify.yml", WORKFLOW, TRACKS),
    StarterFile("AGENTS.md", AGENTS, AGENT_HOOK_TRACKS),
    *(
        StarterFile(
            managed_file.relative_path,
            hook_manifest.render_scaffold(managed_file),
            AGENT_HOOK_TRACKS,
        )
        for managed_file in hook_manifest.scaffold_files()
    ),
    StarterFile("package.json", PACKAGE_JSON, (HARDENING_TRACK,)),
)


def starter_files_for_preset(preset: str) -> tuple[StarterFile, ...]:
    """Return starter files with preset-specific maintainer config."""

    config_file = StarterFile(
        STARTER_CONFIG_PATH,
        apply_preset(STARTER_PYPROJECT, preset),
        TRACKS,
    )
    return (config_file, *STATIC_STARTER_FILES)


def ci_starter_files() -> tuple[StarterFile, ...]:
    """Return starter files needed for GitHub Actions-only adoption."""

    return tuple(
        starter for starter in STATIC_STARTER_FILES if starter.path in CI_ONLY_STARTER_PATHS
    )


# docsync:evidence.end evidence.readme.adoption_track_templates
