"""Starter repository files for package-first initialization."""

from __future__ import annotations

import textwrap
from dataclasses import dataclass

from agent_client_hooks import templates as hook_templates
from agent_maintainer.core.scaffold.presets import apply_preset
from agent_maintainer.core.scaffold.template_config import STARTER_PYPROJECT

CORE_TRACK = "core"
AGENT_TRACK = "agent"
HARDENING_TRACK = "hardening"
TRACKS = (CORE_TRACK, AGENT_TRACK, HARDENING_TRACK)
AGENT_HOOK_TRACKS = (AGENT_TRACK, HARDENING_TRACK)

DEV_DEPENDENCIES = "agent-maintainer[core]\n"

PRE_COMMIT_CONFIG = textwrap.dedent(
    """\
    repos:
      - repo: local
        hooks:
          - id: agent-maintainer-precommit
            name: Agent Maintainer precommit
            entry: >-
              env PYTHONDONTWRITEBYTECODE=1 python3 -m agent_maintainer
              verify --profile precommit --base-ref HEAD --staged
            language: system
            pass_filenames: false
    """
)

WORKFLOW = textwrap.dedent(
    """\
    name: verify

    on:
      pull_request:
      push:
        branches: [main]

    permissions:
      contents: read

    jobs:
      verify:
        runs-on: ubuntu-latest
        env:
          PYTHONDONTWRITEBYTECODE: "1"
        steps:
          - name: Checkout
            uses: actions/checkout@v7
            with:
              fetch-depth: 0
              persist-credentials: false
          - name: Set up Python
            uses: actions/setup-python@v6.2.0
            with:
              python-version: "3.11"
          - name: Install project and Agent Maintainer tools
            run: |
              python -m pip install --upgrade pip
              if [ -f config/dev-lock.txt ]; then
                python -m pip install -r config/dev-lock.txt
              fi
              if [ -f config/dev-dependencies.txt ]; then
                python -m pip install -r config/dev-dependencies.txt
              fi
              python -m pip install -e .
              if [ -f package.json ]; then
                npm ci
              fi
          - name: Verify
            run: |
              BASE_REF="origin/${GITHUB_BASE_REF:-main}"
              python3 -m agent_maintainer verify --profile ci \\
                --base-ref "$BASE_REF" --compare-branch "$BASE_REF"
    """
)

AGENTS = textwrap.dedent(
    """\
    # Repository maintenance

    Read `AGENTS.agent-maintainer.md` before changing code when it exists. That
    file is generated by `python3 -m agent_maintainer guidance` from
    `[tool.agent_maintainer]`.

    Before finishing a code change, run:

    ```bash
    python3 -m agent_maintainer verify --profile precommit
    ```

    For larger changes, run:

    ```bash
    python3 -m agent_maintainer verify --profile full
    ```
    """
)

PACKAGE_JSON = textwrap.dedent(
    """\
    {
      "name": "agent-maintainer-project",
      "private": true,
      "devDependencies": {
        "@taplo/cli": "0.7.0",
        "markdownlint-cli2": "0.22.1"
      }
    }
    """
)


@dataclass(frozen=True)
class StarterFile:
    """One initializer file."""

    path: str
    content: str
    tracks: tuple[str, ...]


STARTER_CONFIG_PATH = "config/pyproject.agent-maintainer.toml"

STATIC_STARTER_FILES = (
    StarterFile("config/dev-dependencies.txt", DEV_DEPENDENCIES, TRACKS),
    StarterFile(".pre-commit-config.yaml", PRE_COMMIT_CONFIG, TRACKS),
    StarterFile(".github/workflows/verify.yml", WORKFLOW, TRACKS),
    StarterFile("AGENTS.md", AGENTS, AGENT_HOOK_TRACKS),
    StarterFile(
        ".codex/config.toml",
        hook_templates.codex_config_file(),
        AGENT_HOOK_TRACKS,
    ),
    StarterFile(
        ".codex/hooks/post_edit_fast_gate.py",
        hook_templates.codex_post_hook(),
        AGENT_HOOK_TRACKS,
    ),
    StarterFile(
        ".codex/hooks/stop_full_verify.py",
        hook_templates.codex_stop_hook(),
        AGENT_HOOK_TRACKS,
    ),
    StarterFile(
        ".codex/hooks/hook_audit.py",
        hook_templates.hook_audit_shim(),
        AGENT_HOOK_TRACKS,
    ),
    StarterFile(
        ".claude/settings.json",
        hook_templates.claude_settings(),
        AGENT_HOOK_TRACKS,
    ),
    StarterFile(
        ".claude/hooks/post_tool_use.py",
        hook_templates.claude_post_hook(),
        AGENT_HOOK_TRACKS,
    ),
    StarterFile(
        ".claude/hooks/stop.py",
        hook_templates.claude_stop_hook(),
        AGENT_HOOK_TRACKS,
    ),
    StarterFile(
        ".claude/hooks/subagent_stop.py",
        hook_templates.claude_subagent_stop_hook(),
        AGENT_HOOK_TRACKS,
    ),
    StarterFile("package.json", PACKAGE_JSON, (HARDENING_TRACK,)),
)


def starter_files_for_preset(preset: str) -> tuple[StarterFile, ...]:
    """Return starter files with preset-specific maintainer config."""

    config_file = StarterFile(
        STARTER_CONFIG_PATH,
        apply_preset(STARTER_PYPROJECT, preset),
        TRACKS,
    )
    return (config_file, *STATIC_STARTER_FILES)
