"""Generate human and machine-readable configuration capability references."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict, is_dataclass
from pathlib import Path
from typing import cast

from agent_maintainer.config import registry
from agent_maintainer.core.structured_values import json_object

REFERENCE_PATH = Path("docs/configuration-reference.md")
CAPABILITIES_PATH = Path("config/agent-maintainer-capabilities.json")
CAPABILITY_SCHEMA_VERSION = 1
SUCCESS_STATUS = 0
DRIFT_STATUS = 1


def capability_payload() -> dict[str, object]:
    """Return the complete stable capability payload."""

    return {
        "schema_version": CAPABILITY_SCHEMA_VERSION,
        "precedence": ["defaults", "mode", "file", "environment", "command_line"],
        "nested_tables": {
            "diagnostics": sorted(registry.DIAGNOSTIC_KEYS),
            "workspaces.*": sorted(registry.WORKSPACE_KEYS),
            "file_baselines": sorted(registry.FILE_BASELINE_KEYS),
            "file_baselines.groups.*": sorted(registry.FILE_BASELINE_GROUP_KEYS),
            "java": sorted(registry.JAVA_KEYS),
            "java.reports.*": sorted(registry.JAVA_REPORT_KEYS),
        },
        "runtime_environment": sorted(registry.NON_CONFIG_ENV_VARS),
        "nested_environment": {"java.enabled": registry.JAVA_ENABLED_ENV},
        "fields": [_field_payload(spec) for spec in registry.FIELD_SPECS.values()],
    }


def _field_payload(spec: registry.ConfigFieldSpec) -> dict[str, object]:
    return {
        "name": spec.field_name,
        "toml_key": spec.toml_key,
        "toml_aliases": list(spec.toml_aliases),
        "value_kind": spec.value_kind,
        "default": _json_value(spec.default_value),
        "environment": spec.env_var or None,
        "environment_style": spec.env_style if spec.env_var else None,
        "cli_override": spec.cli_override,
        "constraints": _constraint_payload(spec),
        "label": spec.docs_label,
        "description": spec.description,
        "stability": spec.stability,
    }


def _constraint_payload(spec: registry.ConfigFieldSpec) -> dict[str, object]:
    return {
        "choices": sorted(spec.choices),
        "minimum": spec.minimum,
        "maximum": spec.maximum,
        "minimum_exclusive": spec.minimum_exclusive,
        "repository_relative_path": spec.path_value,
        "verification_profiles": spec.profile_values,
        "allow_empty": spec.allow_empty,
    }


def _json_value(value: object) -> object:
    if is_dataclass(value) and not isinstance(value, type):
        return _json_value(asdict(value))
    if isinstance(value, dict):
        return {str(key): _json_value(item) for key, item in value.items()}
    if isinstance(value, tuple):
        values = cast(tuple[object, ...], value)
        return [_json_value(item) for item in values]
    return value


def render_capabilities_json() -> str:
    """Render deterministic machine-readable capability metadata."""

    rendered = json.dumps(capability_payload(), indent=2, sort_keys=True)
    return f"{rendered}\n"


def render_reference_markdown() -> str:
    """Render the generated public configuration reference."""

    lines = [
        "# Agent Maintainer Configuration Reference",
        "",
        "<!-- Generated by `python -m agent_maintainer.config.reference`; do not edit. -->",
        "",
        "This reference is generated from the same registry used for coercion and validation.",
        "Configuration precedence is defaults, mode preset, file, environment, then CLI.",
        "",
        "## Nested Tables",
        "",
        "| Table | Accepted child keys |",
        "|---|---|",
        *_nested_table_rows(),
        "",
        "## Nested Environment Overrides",
        "",
        "| TOML key | Environment |",
        "|---|---|",
        *_nested_environment_rows(),
        "",
        "## Fields",
        "",
        "| TOML key | Type | Default | Environment | CLI | Constraints | Stability |",
        "|---|---|---|---|---|---|---|",
        *(_field_markdown_row(spec) for spec in registry.FIELD_SPECS.values()),
        "",
        "Regenerate after registry changes:",
        "",
        "```bash",
        "python -m agent_maintainer.config.reference",
        "python -m agent_maintainer.config.reference --check",
        "```",
        "",
    ]
    return "\n".join(lines)


def _nested_table_rows() -> list[str]:
    nested = json_object(capability_payload()["nested_tables"])
    if nested is None:
        return []
    return [f"| `{table}` | {_markdown_value(keys)} |" for table, keys in nested.items()]


def _nested_environment_rows() -> list[str]:
    nested = json_object(capability_payload()["nested_environment"])
    if nested is None:
        return []
    return [f"| `{key}` | `{value}` |" for key, value in nested.items()]


def _field_markdown_row(spec: registry.ConfigFieldSpec) -> str:
    values = (
        f"`{spec.toml_key}`",
        spec.value_kind,
        _markdown_value(_json_value(spec.default_value)),
        f"`{spec.env_var}`" if spec.env_var else "—",
        spec.cli_override,
        _constraint_text(spec),
        spec.stability,
    )
    cells = " | ".join(values)
    return f"| {cells} |"


def _constraint_text(spec: registry.ConfigFieldSpec) -> str:
    constraints: list[str] = []
    if spec.choices:
        choices = ", ".join(sorted(spec.choices))
        constraints.append(f"choices: {choices}")
    if spec.minimum is not None:
        relation = ">" if spec.minimum_exclusive else ">="
        minimum = format(spec.minimum, "g")
        constraints.append(f"{relation} {minimum}")
    if spec.maximum is not None:
        maximum = format(spec.maximum, "g")
        constraints.append(f"<= {maximum}")
    if spec.path_value:
        constraints.append("repository-relative path")
    if spec.profile_values:
        constraints.append("known profiles")
    if spec.toml_aliases:
        aliases = ", ".join(spec.toml_aliases)
        constraints.append(f"aliases: {aliases}")
    return "; ".join(constraints) or "—"


def _markdown_value(value: object) -> str:
    rendered = json.dumps(value, sort_keys=True, separators=(",", ":"))
    escaped = rendered.replace("|", r"\|")
    return f"`{escaped}`"


def rendered_files() -> dict[Path, str]:
    """Return generated repository paths and their current contents."""

    return {
        REFERENCE_PATH: render_reference_markdown(),
        CAPABILITIES_PATH: render_capabilities_json(),
    }


def write_generated(repo_root: Path) -> tuple[Path, ...]:
    """Write all generated references beneath a repository root."""

    written: list[Path] = []
    for relative_path, content in rendered_files().items():
        destination = repo_root / relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")
        written.append(destination)
    return tuple(written)


def outdated_generated(repo_root: Path) -> tuple[Path, ...]:
    """Return generated files that are absent or differ from the registry."""

    return tuple(
        relative_path
        for relative_path, expected in rendered_files().items()
        if _read_text(repo_root / relative_path) != expected
    )


def _read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return ""


def parse_args(argv: list[str] | None) -> argparse.Namespace:
    """Parse deterministic generator options."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated files drift.")
    parser.add_argument("--root", type=Path, default=Path.cwd(), help="Repository root.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Write generated files or check them for drift."""

    args = parse_args(argv)
    if args.check:
        outdated = outdated_generated(args.root)
        if outdated:
            for path in outdated:
                print(f"OUTDATED {path}")
            return DRIFT_STATUS
        print("Configuration references are current.")
        return SUCCESS_STATUS
    for path in write_generated(args.root):
        print(f"WROTE {path}")
    return SUCCESS_STATUS


if __name__ == "__main__":
    sys.exit(main())
