"""Tests file context safety refusals."""

from __future__ import annotations

import os
from pathlib import Path

import pytest

import agent_context.reading.file_safety as file_safety_module
import agent_maintainer.context.reading.file_safety as old_file_safety
from agent_context.reading.file_safety import MAX_FILE_BYTES, inspect_file, read_text_file

MINIFIED_JSON_CHARS = 2_100


def test_old_context_file_safety_imports_delegate_to_agent_context() -> None:
    """Old file-safety import path delegates to extracted package."""

    assert old_file_safety.FileSafety is file_safety_module.FileSafety
    assert old_file_safety.inspect_file is file_safety_module.inspect_file
    assert old_file_safety.inspect_path is file_safety_module.inspect_path
    assert old_file_safety.inspect_text is file_safety_module.inspect_text
    assert old_file_safety.refused_path is file_safety_module.refused_path
    assert old_file_safety.looks_generated is file_safety_module.looks_generated


def test_binary_file_is_refused(tmp_path: Path) -> None:
    """Binary files are not expanded."""

    path = tmp_path / "data.bin"
    path.write_bytes(b"abc\x00def")

    result = inspect_file(path)

    assert result.allowed is False
    assert result.reason == "binary file"


def test_non_utf8_file_is_refused(tmp_path: Path) -> None:
    """Non-UTF-8 files are not expanded."""

    path = tmp_path / "latin.txt"
    path.write_bytes(b"\xff\xfe")

    result = inspect_file(path)

    assert result.allowed is False
    assert result.reason == "non-UTF-8 file"


def test_missing_file_is_refused(tmp_path: Path) -> None:
    """Unreadable paths are refused."""

    result = inspect_file(tmp_path / "missing.py")

    assert result.allowed is False
    assert result.reason.startswith("unreadable:")


def test_generated_file_is_refused(tmp_path: Path) -> None:
    """Generated files are refused."""

    path = tmp_path / "generated.py"
    path.write_text("# Generated by tool\nvalue = 1", encoding="utf-8")

    result = inspect_file(path)

    assert result.allowed is False
    assert result.reason == "generated file"


def test_regular_text_file_is_allowed(tmp_path: Path) -> None:
    """Regular UTF-8 files are allowed."""

    path = tmp_path / "source.py"
    path.write_text("value = 1", encoding="utf-8")

    result = inspect_file(path)

    assert result.allowed is True
    assert result.reason == "ok"


def test_lock_file_is_refused(tmp_path: Path) -> None:
    """Lock files are refused."""

    path = tmp_path / "poetry.lock"
    path.write_text("package = []", encoding="utf-8")

    result = inspect_file(path)

    assert result.allowed is False
    assert "lock" in result.reason


def test_symlink_is_refused(tmp_path: Path) -> None:
    """Symlinks are refused."""

    target = tmp_path / "target.py"
    target.write_text("value = 1", encoding="utf-8")
    path = tmp_path / "link.py"
    path.symlink_to(target)

    result = inspect_file(path)

    assert result.allowed is False
    assert result.reason == "symlink"


def test_minified_json_is_refused(tmp_path: Path) -> None:
    """Minified JSON is refused as unsafe context."""

    path = tmp_path / "large.json"
    path.write_text("{" + '"value":"' + ("x" * MINIFIED_JSON_CHARS) + '"}', encoding="utf-8")

    result = inspect_file(path)

    assert result.allowed is False
    assert result.reason == "minified JSON"


@pytest.mark.parametrize(
    "name",
    (
        ".docker/config.json",
        ".env",
        ".env.production",
        ".envrc",
        ".git-credentials",
        ".kube/config",
        "auth.json",
        "client_secret_123.json",
        "credentials.json",
        "credentials.yml",
        "id_rsa",
        "kubeconfig",
        "private-key.pem",
        "secret.json",
        "secrets.yaml",
        "terraform.tfstate.backup",
        "terraform.tfvars",
        "terraform.tfvars.json",
        "token.json",
    ),
)
def test_sensitive_file_names_are_refused_without_open(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    name: str,
) -> None:
    """Credential-bearing names are denied before file contents are opened."""

    path = tmp_path / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("secret", encoding="utf-8")
    monkeypatch.setattr(file_safety_module.os, "open", forbidden_open)

    result = inspect_file(path)

    assert result.allowed is False
    assert result.reason == "sensitive path"


def test_sparse_oversized_file_is_refused_without_open(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Sparse files over the byte ceiling are rejected from lstat metadata."""

    path = tmp_path / "oversized.txt"
    with path.open("wb") as stream:
        stream.seek(MAX_FILE_BYTES)
        stream.write(b"x")
    monkeypatch.setattr(file_safety_module.os, "open", forbidden_open)

    result = inspect_file(path)

    assert result.allowed is False
    assert "byte limit" in result.reason


@pytest.mark.skipif(not hasattr(os, "mkfifo"), reason="FIFO support is POSIX-only")
def test_fifo_is_refused_without_opening_or_blocking(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """FIFO metadata is refused before the bounded reader opens it."""

    path = tmp_path / "context.pipe"
    os.mkfifo(path)
    monkeypatch.setattr(file_safety_module.os, "open", forbidden_open)

    result = inspect_file(path)

    assert result.allowed is False
    assert result.reason == "not a regular file"


def test_directory_is_refused_as_non_regular(tmp_path: Path) -> None:
    """Directories cannot enter the text reader."""

    result = inspect_file(tmp_path)

    assert result.allowed is False
    assert result.reason == "not a regular file"


def test_symlink_parent_is_refused(tmp_path: Path) -> None:
    """A symlinked parent cannot redirect an otherwise regular file read."""

    outside = tmp_path / "outside"
    outside.mkdir()
    (outside / "source.py").write_text("secret = True", encoding="utf-8")
    redirect = tmp_path / "redirect"
    redirect.symlink_to(outside, target_is_directory=True)

    result = inspect_file(redirect / "source.py")

    assert result.allowed is False
    assert result.reason == "symlink parent"


def test_safe_text_reader_uses_one_descriptor(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Safety inspection and UTF-8 decoding share one bounded file read."""

    path = tmp_path / "source.py"
    path.write_text("value = 1\n", encoding="utf-8")
    real_open = file_safety_module.os.open
    opened: list[Path] = []

    def counted_open(target: Path, flags: int) -> int:
        opened.append(Path(target))
        return real_open(target, flags)

    monkeypatch.setattr(file_safety_module.os, "open", counted_open)

    result = read_text_file(path)

    assert result.safety.allowed is True
    assert result.text == "value = 1\n"
    assert opened == [path]


def forbidden_open(*args: object, **kwargs: object) -> int:
    """Fail if a path-level refusal attempts content access."""

    raise AssertionError(f"unexpected open: {args!r} {kwargs!r}")
