"""Tests file context safety refusals."""

from __future__ import annotations

from pathlib import Path

import agent_context.reading.file_safety as file_safety_module
import agent_maintainer.context.reading.file_safety as old_file_safety
from agent_context.reading.file_safety import inspect_file

MINIFIED_JSON_CHARS = 2_100


def test_old_context_file_safety_imports_delegate_to_agent_context() -> None:
    """Old file-safety import path delegates to extracted package."""

    assert old_file_safety.FileSafety is file_safety_module.FileSafety
    assert old_file_safety.inspect_file is file_safety_module.inspect_file
    assert old_file_safety.inspect_path is file_safety_module.inspect_path
    assert old_file_safety.inspect_text is file_safety_module.inspect_text
    assert old_file_safety.refused_path is file_safety_module.refused_path
    assert old_file_safety.looks_generated is file_safety_module.looks_generated


def test_binary_file_is_refused(tmp_path: Path) -> None:
    """Binary files are not expanded."""

    path = tmp_path / "data.bin"
    path.write_bytes(b"abc\x00def")

    result = inspect_file(path)

    assert result.allowed is False
    assert result.reason == "binary file"


def test_non_utf8_file_is_refused(tmp_path: Path) -> None:
    """Non-UTF-8 files are not expanded."""

    path = tmp_path / "latin.txt"
    path.write_bytes(b"\xff\xfe")

    result = inspect_file(path)

    assert result.allowed is False
    assert result.reason == "non-UTF-8 file"


def test_missing_file_is_refused(tmp_path: Path) -> None:
    """Unreadable paths are refused."""

    result = inspect_file(tmp_path / "missing.py")

    assert result.allowed is False
    assert result.reason.startswith("unreadable:")


def test_generated_file_is_refused(tmp_path: Path) -> None:
    """Generated files are refused."""

    path = tmp_path / "generated.py"
    path.write_text("# Generated by tool\nvalue = 1", encoding="utf-8")

    result = inspect_file(path)

    assert result.allowed is False
    assert result.reason == "generated file"


def test_regular_text_file_is_allowed(tmp_path: Path) -> None:
    """Regular UTF-8 files are allowed."""

    path = tmp_path / "source.py"
    path.write_text("value = 1", encoding="utf-8")

    result = inspect_file(path)

    assert result.allowed is True
    assert result.reason == "ok"


def test_lock_file_is_refused(tmp_path: Path) -> None:
    """Lock files are refused."""

    path = tmp_path / "poetry.lock"
    path.write_text("package = []", encoding="utf-8")

    result = inspect_file(path)

    assert result.allowed is False
    assert "lock" in result.reason


def test_symlink_is_refused(tmp_path: Path) -> None:
    """Symlinks are refused."""

    target = tmp_path / "target.py"
    target.write_text("value = 1", encoding="utf-8")
    path = tmp_path / "link.py"
    path.symlink_to(target)

    result = inspect_file(path)

    assert result.allowed is False
    assert result.reason == "symlink"


def test_minified_json_is_refused(tmp_path: Path) -> None:
    """Minified JSON is refused as unsafe context."""

    path = tmp_path / "large.json"
    path.write_text("{" + '"value":"' + ("x" * MINIFIED_JSON_CHARS) + '"}', encoding="utf-8")

    result = inspect_file(path)

    assert result.allowed is False
    assert result.reason == "minified JSON"
