"""Go ecosystem file classification helpers."""

from __future__ import annotations

from pathlib import Path

from agent_maintainer.ecosystems.models import FileClassification, FileRole

ECOSYSTEM_NAME = "go"
SOURCE_EXTENSION = ".go"
TEST_SUFFIX = "_test.go"
IGNORED_PARTS = frozenset(
    (
        ".git",
        ".hg",
        ".svn",
        "bin",
        "build",
        "coverage",
        "dist",
        "vendor",
    ),
)
GENERATED_PARTS = frozenset(("generated", "__generated__"))
GENERATED_SUFFIXES = (".pb.go", "_gen.go", "_generated.go")
GENERATED_MARKERS = (
    "@generated",
    "code generated",
    "do not edit",
)
CONFIG_NAMES = frozenset(
    (
        ".golangci.yml",
        ".golangci.yaml",
        "go.env",
        "go.work",
    ),
)
DEPENDENCY_NAMES = frozenset(("go.mod", "go.sum", "go.work.sum"))
DOC_EXTENSIONS = frozenset((".md", ".rst", ".txt"))


def classify_path(path: str | Path) -> FileClassification | None:
    """Classify a Go ecosystem path when the provider can own it."""
    repo_path = Path(path)
    lower_name = repo_path.name.lower()
    lower_parts = tuple(part.lower() for part in repo_path.parts)

    non_source = _classify_non_source(repo_path, lower_name, lower_parts)
    if non_source is not None:
        return non_source

    if lower_name.endswith(SOURCE_EXTENSION):
        return _classify_go_source(repo_path, lower_name, lower_parts)

    return None


def _classify_non_source(
    repo_path: Path,
    lower_name: str,
    lower_parts: tuple[str, ...],
) -> FileClassification | None:
    """Classify ignored, dependency, config, and docs paths."""
    if any(part in IGNORED_PARTS for part in lower_parts):
        return FileClassification(
            str(repo_path),
            ECOSYSTEM_NAME,
            FileRole.IGNORED,
            ignored=True,
            reason="ignored Go dependency or build path",
        )

    if lower_name in DEPENDENCY_NAMES:
        return FileClassification(str(repo_path), ECOSYSTEM_NAME, FileRole.DEPENDENCY)

    if lower_name in CONFIG_NAMES:
        return FileClassification(str(repo_path), ECOSYSTEM_NAME, FileRole.CONFIG)

    if repo_path.suffix.lower() in DOC_EXTENSIONS:
        return FileClassification(str(repo_path), ECOSYSTEM_NAME, FileRole.DOCS)

    return None


def _classify_go_source(
    repo_path: Path,
    lower_name: str,
    lower_parts: tuple[str, ...],
) -> FileClassification:
    """Classify a Go source file as test, generated, or source."""
    if _looks_generated(lower_name, lower_parts):
        return FileClassification(
            str(repo_path),
            ECOSYSTEM_NAME,
            FileRole.GENERATED,
            generated=True,
            reason="generated Go source",
        )
    if lower_name.endswith(TEST_SUFFIX):
        return FileClassification(str(repo_path), ECOSYSTEM_NAME, FileRole.TEST)
    return FileClassification(str(repo_path), ECOSYSTEM_NAME, FileRole.SOURCE)


def _looks_generated(lower_name: str, lower_parts: tuple[str, ...]) -> bool:
    """Return whether a Go path appears generated by name or folder."""
    return (
        any(part in GENERATED_PARTS for part in lower_parts)
        or any(lower_name.endswith(suffix) for suffix in GENERATED_SUFFIXES)
        or any(marker in lower_name for marker in GENERATED_MARKERS)
    )
