"""Compatibility shim for PR summary support helpers."""

from agent_run_artifacts import pr_summary_support

MAX_PR_SUMMARY_CHARS = pr_summary_support.MAX_PR_SUMMARY_CHARS
MAX_FAILURES = pr_summary_support.MAX_FAILURES
MAX_OUTPUT_LINES = pr_summary_support.MAX_OUTPUT_LINES
MAX_SUMMARY_LINES = pr_summary_support.MAX_SUMMARY_LINES
summary_expansion_commands = pr_summary_support.summary_expansion_commands
summary_rerun_command = pr_summary_support.summary_rerun_command
failed_results = pr_summary_support.failed_results
matching_results = pr_summary_support.matching_results
first_result = pr_summary_support.first_result
result_status_lines = pr_summary_support.result_status_lines
result_state = pr_summary_support.result_state
compact_output_bullets = pr_summary_support.compact_output_bullets
compact_output_lines = pr_summary_support.compact_output_lines
bounded_summary = pr_summary_support.bounded_summary
preserved_expansion_footer = pr_summary_support.preserved_expansion_footer
