"""Compatibility exports for agent-client hook config merging."""

from agent_client_hooks import merge as _merge

CODEX_HOOK_FEATURE = _merge.CODEX_HOOK_FEATURE
ensure_codex_hooks_feature = _merge.ensure_codex_hooks_feature
features_section_bounds = _merge.features_section_bounds
is_orphan_previous_agent_hook_parent = _merge.is_orphan_previous_agent_hook_parent
is_parent_hook_section = _merge.is_parent_hook_section
is_previous_agent_codex_hook_section = _merge.is_previous_agent_codex_hook_section
merge_claude_settings = _merge.merge_claude_settings
merge_codex_config = _merge.merge_codex_config
normalize_feature_section = _merge.normalize_feature_section
previous_agent_codex_hook_indexes = _merge.previous_agent_codex_hook_indexes
split_toml_sections = _merge.split_toml_sections
strip_managed_block = _merge.strip_managed_block
strip_previous_agent_codex_hooks = _merge.strip_previous_agent_codex_hooks
