"""Characterization tests for current Python policy checks."""

from __future__ import annotations

from pathlib import Path

from agent_maintainer.checks import (
    change_budget,
    file_lengths,
    structure,
    suppression_budget,
)
from agent_maintainer.core.config import MaintainerConfig

STRUCTURE_FINDING_COUNT = 4
NOQA_MARKER = "# " + "noqa"
TYPE_IGNORE_MARKER = "# " + "type: " + "ignore"
PYRIGHT_MARKER = "# " + "pyright: " + "reportPrivateUsage=false"
COVERAGE_MARKER = "# " + "pragma: " + "no cover"


def test_change_budget_python_source_and_test_classification() -> None:
    """Pin current Python source/test path classification."""
    config = MaintainerConfig(
        source_roots=("src", "scripts"),
        test_roots=("tests",),
    )
    changes = [
        change_budget.FileChange("src/pkg/app.py", 4, 1),
        change_budget.FileChange("scripts/tool.py", 2, 0),
        change_budget.FileChange("tests/test_app.py", 3, 0),
        change_budget.FileChange("src/pkg/__init__.py", 1, 0),
        change_budget.FileChange("src/pkg/app.txt", 9, 0),
        change_budget.FileChange("docs/demo.py", 7, 0),
    ]

    assert change_budget.is_python_source("src/pkg/app.py", config.source_roots)
    assert change_budget.is_python_source(
        "scripts/tool.py",
        config.source_roots,
    )
    assert not change_budget.is_python_source(
        "tests/test_app.py",
        config.source_roots,
    )
    assert change_budget.is_python_test("tests/test_app.py", config.test_roots)
    assert not change_budget.is_python_test("docs/demo.py", config.test_roots)

    source_changes, test_changes = change_budget.changed_python_files(
        changes,
        config,
    )

    assert [change.path for change in source_changes] == [
        "src/pkg/app.py",
        "scripts/tool.py",
    ]
    assert [change.path for change in test_changes] == ["tests/test_app.py"]


def test_file_length_python_discovery_and_generated_exclusion(
    tmp_path: Path,
) -> None:
    """Pin current file-length behavior before generic classifiers exist."""
    source = tmp_path / "src" / "pkg"
    source.mkdir(parents=True)
    kept = source / "kept.py"
    generated = source / "generated.py"
    non_python = source / "README.md"
    cache_file = source / "__pycache__" / "cached.py"

    kept.write_text("x = 1\n# comment\ny = 2\n", encoding="utf-8")
    generated.write_text(
        "# Automatically generated by tool\nx = 1\n",
        encoding="utf-8",
    )
    non_python.write_text("# docs\n", encoding="utf-8")
    cache_file.parent.mkdir()
    cache_file.write_text("x = 1\n", encoding="utf-8")

    expanded = file_lengths.expand_explicit_paths([str(tmp_path / "src")])
    eligible = file_lengths.eligible_python_paths(
        expanded,
        include_generated=False,
    )

    assert kept in eligible
    assert generated not in eligible
    assert cache_file not in eligible
    assert non_python not in expanded
    assert file_lengths.count_lines(kept) == (3, 2)


def test_suppression_budget_python_suppression_classification() -> None:
    """Pin broad-vs-specific Python suppression rules."""
    broad_noqa = suppression_budget.classify(
        "src/pkg/app.py",
        f"value = call() {NOQA_MARKER}",
    )
    specific_noqa = suppression_budget.classify(
        "src/pkg/app.py",
        f"value = call() {NOQA_MARKER}: F401",
    )
    broad_type_ignore = suppression_budget.classify(
        "src/pkg/app.py",
        f"value = call() {TYPE_IGNORE_MARKER}",
    )
    specific_type_ignore = suppression_budget.classify(
        "src/pkg/app.py",
        f"value = call() {TYPE_IGNORE_MARKER}[assignment]",
    )
    pyright_disable = suppression_budget.classify(
        "src/pkg/app.py",
        PYRIGHT_MARKER,
    )

    assert [issue.reason for issue in broad_noqa] == [
        "broad noqa without specific rule code",
    ]
    assert specific_noqa == []
    assert [issue.reason for issue in broad_type_ignore] == [
        "broad type ignore without specific error code",
    ]
    assert specific_type_ignore == []
    assert [issue.reason for issue in pyright_disable] == [
        "file-level pyright diagnostic disable",
    ]
    assert suppression_budget.contains_suppression(COVERAGE_MARKER)


def test_structure_cohesion_uses_python_files_by_folder(tmp_path: Path) -> None:
    """Pin current structure-cohesion Python file grouping."""
    package = tmp_path / "src" / "pkg"
    package.mkdir(parents=True)
    for name in (
        "user_model.py",
        "user_service.py",
        "user_repository.py",
        "course_model.py",
    ):
        (package / name).write_text("value = 1\n", encoding="utf-8")
    (package / "README.md").write_text("# docs\n", encoding="utf-8")
    (package / "__pycache__").mkdir()
    (package / "__pycache__" / "cached.py").write_text(
        "value = 1\n",
        encoding="utf-8",
    )

    files = structure.python_files(
        (str(tmp_path / "src"),),
        ("**/__pycache__/**",),
    )
    findings = structure.structure_findings(
        files,
        warn_threshold=4,
        block_threshold=0,
        patterns=("^user_", "_model$"),
        cluster_min=2,
    )

    assert sorted(path.name for path in files) == [
        "course_model.py",
        "user_model.py",
        "user_repository.py",
        "user_service.py",
    ]
    assert len(findings) == 1
    assert findings[0].severity == "WARN"
    assert findings[0].count == STRUCTURE_FINDING_COUNT
    assert any("pattern '^user_'" in hint for hint in findings[0].hints)
