"""Safety checks for file context expansion."""

from __future__ import annotations

import os
import stat
from dataclasses import dataclass
from pathlib import Path

MAX_JSON_LINE_LENGTH = 2_000
MAX_MINIFIED_JSON_LINES = 2
MAX_FILE_BYTES = 1_048_576
TEXT_SAMPLE_BYTES = 4_096
LOCK_FILE_NAMES = frozenset(
    (
        "package-lock.json",
        "pnpm-lock.yaml",
        "poetry.lock",
        "uv.lock",
        "Pipfile.lock",
    ),
)
REFUSED_SUFFIXES = frozenset((".ipynb", ".pyc", ".pyo"))
REFUSED_PARTS = frozenset(
    (
        ".git",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".tox",
        ".venv",
        "__pycache__",
        "build",
        "dist",
        "htmlcov",
        "node_modules",
        "venv",
    ),
)
GENERATED_MARKERS = ("generated", "autogenerated", "do not edit")
SENSITIVE_DIRECTORY_NAMES = frozenset(
    (
        ".aws",
        ".azure",
        ".docker",
        ".gcloud",
        ".gnupg",
        ".kube",
        ".ssh",
        ".terraform",
    )
)
SENSITIVE_FILE_NAMES = frozenset(
    (
        ".envrc",
        ".git-credentials",
        ".netrc",
        ".npmrc",
        ".pypirc",
        "application_default_credentials.json",
        "auth.json",
        "credentials",
        "credentials.json",
        "credentials.yaml",
        "credentials.yml",
        "id_dsa",
        "id_ecdsa",
        "id_ed25519",
        "id_rsa",
        "kubeconfig",
        "secret.json",
        "secret.yaml",
        "secret.yml",
        "secrets.json",
        "secrets.yaml",
        "secrets.yml",
        "service-account.json",
        "service_account.json",
        "token.json",
    ),
)
SENSITIVE_SUFFIXES = frozenset(
    (
        ".jks",
        ".key",
        ".kdbx",
        ".keystore",
        ".ovpn",
        ".p12",
        ".pem",
        ".pfx",
        ".tfstate",
        ".tfvars",
    )
)


@dataclass(frozen=True)
class FileSafety:
    """File context safety decision."""

    allowed: bool
    reason: str
    path: Path


@dataclass(frozen=True)
class SafeTextRead:
    """One-pass bounded text read and its safety decision."""

    safety: FileSafety
    text: str | None


def inspect_file(path: Path) -> FileSafety:
    """Return safety decision for a file path."""

    return read_text_file(path).safety


def inspect_path(path: Path, *, max_bytes: int = MAX_FILE_BYTES) -> FileSafety | None:
    """Return path-level refusal when applicable."""

    reason: str | None = None
    if refused_path(path):
        reason = "refused generated/cache/lock path"
    elif sensitive_path(path):
        reason = "sensitive path"
    elif has_symlink_parent(path):
        reason = "symlink parent"
    else:
        reason = _stat_refusal_reason(path, max_bytes=max_bytes)
    if reason is None:
        return None
    return denied(path, reason)


def _stat_refusal_reason(path: Path, *, max_bytes: int) -> str | None:
    """Return a metadata refusal reason without opening file content."""

    try:
        path_stat = path.lstat()
    except OSError as exc:
        return f"unreadable: {exc}"
    if stat.S_ISLNK(path_stat.st_mode):
        return "symlink"
    if not stat.S_ISREG(path_stat.st_mode):
        return "not a regular file"
    if path_stat.st_size > max_bytes:
        return f"file exceeds {max_bytes} byte limit"
    return None


def read_file_bytes(
    path: Path,
    *,
    max_bytes: int = MAX_FILE_BYTES,
) -> bytes | FileSafety:
    """Return at most ``max_bytes`` file bytes from one safe open."""

    path_decision = inspect_path(path, max_bytes=max_bytes)
    if path_decision is not None:
        return path_decision
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    flags |= getattr(os, "O_NONBLOCK", 0)
    try:
        descriptor = os.open(path, flags)
    except OSError as exc:
        return denied(path, f"unreadable: {exc}")
    return _read_opened_file(path, descriptor, max_bytes=max_bytes)


def _read_opened_file(path: Path, descriptor: int, *, max_bytes: int) -> bytes | FileSafety:
    """Revalidate and read an already-open descriptor within the byte ceiling."""

    try:
        raw = _read_validated_descriptor(path, descriptor, max_bytes=max_bytes)
    except OSError as exc:
        return denied(path, f"unreadable: {exc}")
    finally:
        os.close(descriptor)
    if isinstance(raw, FileSafety):
        return raw
    if len(raw) > max_bytes:
        return denied(path, f"file exceeds {max_bytes} byte limit")
    return raw


def _read_validated_descriptor(
    path: Path,
    descriptor: int,
    *,
    max_bytes: int,
) -> bytes | FileSafety:
    """Validate and read one already-open regular-file descriptor."""

    opened_stat = os.fstat(descriptor)
    if not stat.S_ISREG(opened_stat.st_mode):
        return denied(path, "not a regular file")
    if opened_stat.st_size > max_bytes:
        return denied(path, f"file exceeds {max_bytes} byte limit")
    return _read_bounded(descriptor, limit=max_bytes + 1)


def read_text_file(
    path: Path,
    *,
    workspace_root: Path | None = None,
    max_bytes: int = MAX_FILE_BYTES,
) -> SafeTextRead:
    """Read and inspect one bounded UTF-8 regular file exactly once."""

    safe_read = read_bounded_utf8_file(
        path,
        workspace_root=workspace_root,
        max_bytes=max_bytes,
    )
    if not safe_read.safety.allowed or safe_read.text is None:
        return safe_read
    text = safe_read.text
    if looks_generated(text):
        safety = denied(path, "generated file")
    elif looks_minified_json(path, text):
        safety = denied(path, "minified JSON")
    else:
        safety = FileSafety(True, "ok", path)
    return SafeTextRead(safety, safe_read.text if safety.allowed else None)


def read_bounded_utf8_file(
    path: Path,
    *,
    workspace_root: Path | None = None,
    max_bytes: int = MAX_FILE_BYTES,
) -> SafeTextRead:
    """Read one bounded regular file as UTF-8 without content-shape policy."""

    read_path = path
    if workspace_root is not None:
        confined = confined_path(path, workspace_root=workspace_root)
        if isinstance(confined, FileSafety):
            return SafeTextRead(confined, None)
        read_path = confined
    raw = read_file_bytes(read_path, max_bytes=max_bytes)
    if isinstance(raw, FileSafety):
        return SafeTextRead(raw, None)
    if is_binary(raw):
        return SafeTextRead(denied(path, "binary file"), None)
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        return SafeTextRead(denied(path, "non-UTF-8 file"), None)
    return SafeTextRead(FileSafety(True, "ok", path), text)


def confined_path(path: Path, *, workspace_root: Path) -> Path | FileSafety:
    """Return a lexical path contained by one canonical workspace root."""

    try:
        root = workspace_root.resolve(strict=True)
    except OSError as exc:
        return denied(path, f"workspace root unavailable: {exc}")
    if not root.is_dir():
        return denied(path, "workspace root is not a directory")
    if ".." in path.parts:
        return denied(path, "path escapes workspace root")
    candidate = path if path.is_absolute() else root / path
    try:
        candidate.relative_to(root)
    except ValueError:
        return denied(path, "path escapes workspace root")
    return candidate


def inspect_text(path: Path, raw: bytes) -> FileSafety:
    """Return content-level safety decision."""

    if is_binary(raw):
        return denied(path, "binary file")
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        return denied(path, "non-UTF-8 file")

    if looks_generated(text):
        return denied(path, "generated file")
    if looks_minified_json(path, text):
        return denied(path, "minified JSON")
    return FileSafety(True, "ok", path)


def denied(path: Path, reason: str) -> FileSafety:
    """Return denied file safety decision."""

    return FileSafety(False, reason, path)


def refused_path(path: Path) -> bool:
    """Return whether path should never be expanded directly."""

    return (
        path.name in LOCK_FILE_NAMES
        or path.suffix in REFUSED_SUFFIXES
        or any(part in REFUSED_PARTS for part in path.parts)
    )


def sensitive_path(path: Path) -> bool:
    """Return whether a path name commonly carries credentials or private keys."""

    lowered_parts = tuple(part.lower() for part in path.parts)
    name = path.name.lower()
    normalized_name = name.replace("-", "_")
    return any(
        (
            any(part in SENSITIVE_DIRECTORY_NAMES for part in lowered_parts),
            name == ".env",
            name.startswith(".env."),
            name in SENSITIVE_FILE_NAMES,
            path.suffix.lower() in SENSITIVE_SUFFIXES,
            "private_key" in normalized_name,
            name.endswith((".tfstate.backup", ".tfvars.json")),
            name.startswith("client_secret") and name.endswith(".json"),
        )
    )


def has_symlink_parent(path: Path) -> bool:
    """Return whether an existing parent component is a symlink."""

    anchor = Path(path.anchor) if path.is_absolute() else Path()
    parts = path.parts[1:] if path.is_absolute() else path.parts
    current = anchor
    for part in parts[:-1]:
        current /= part
        if current.is_symlink():
            return True
    return False


def _read_bounded(descriptor: int, *, limit: int) -> bytes:
    """Read one descriptor once through, stopping at the byte ceiling."""

    chunks: list[bytes] = []
    remaining = limit
    while remaining > 0:
        chunk = os.read(descriptor, remaining)
        if not chunk:
            break
        chunks.append(chunk)
        remaining -= len(chunk)
    return b"".join(chunks)


def is_binary(raw: bytes) -> bool:
    """Return whether byte sample appears binary."""

    return b"\x00" in raw[:TEXT_SAMPLE_BYTES]


def looks_generated(text: str) -> bool:
    """Return whether text appears generated."""

    first_lines = "\n".join(text.splitlines()[:5]).lower()
    return any(marker in first_lines for marker in GENERATED_MARKERS)


def looks_minified_json(path: Path, text: str) -> bool:
    """Return whether JSON text is likely minified and too dense."""

    if path.suffix != ".json":
        return False
    lines = text.splitlines()
    return len(lines) <= MAX_MINIFIED_JSON_LINES and any(
        len(line) > MAX_JSON_LINE_LENGTH for line in lines
    )
