"""Technical Debt Score category constants."""

from __future__ import annotations

LOW_RISK_MAX = 25
MODERATE_RISK_MAX = 50
HIGH_RISK_MAX = 75
MAX_SCORE = 100

REVIEWABILITY_BASE = 15
CHANGE_BUDGET_PENALTY = 20
SOURCE_LENGTH_PENALTY = 15
TRUNCATED_SCAN_PENALTY = 10
REVIEWABLE_LINE_BLOCK = 800
REVIEWABLE_FILE_BLOCK = 20
SOURCE_LENGTH_CAP = 450
EXCELLENT_SOURCE_LENGTH_CAP = 375
REVIEWABILITY_WEIGHT = 14

TESTS_BASE = 5
MISSING_REQUIRED_TESTS_PENALTY = 35
MISSING_TEST_TREE_PENALTY = 25
LOW_COVERAGE_PENALTY = 15
MIN_HEALTHY_COVERAGE = 80
EXCELLENT_COVERAGE = 90
TESTS_WEIGHT = 18

STYLE_BASE = 10
BASIC_TYPE_PENALTY = 15
HIGH_COMPLEXITY_PENALTY = 10
MISSING_WEMAKE_PENALTY = 10
RUFF_COMPLEXITY_CAP = 10
STRICT_TYPE_REDUCTION = 5
STYLE_WEIGHT = 12

ARCHITECTURE_BASE = 5
MISSING_TACH_PENALTY = 30
MISSING_IMPORT_LINTER_PENALTY = 25
ARCHITECTURE_WEIGHT = 14

SECURITY_WEIGHT = 14

DOCS_BASE = 5
MISSING_RELEVANT_DOCS_GATE_PENALTY = 10
DOCS_MIN_SCORE = 5
DOCS_WEIGHT = 10

DIAGNOSTICS_BASE = 5
DIAGNOSTICS_DISABLED_PENALTY = 20
MISSING_GUIDANCE_PENALTY = 12
DIAGNOSTICS_WEIGHT = 10

MUTATION_BASE = 10
MUTATION_DISABLED_PENALTY = 35
MUTATION_RATCHET_PENALTY = 15
HEALTHY_MUTATION_SCORE = 5
MUTATION_WEIGHT = 8

REVIEWABILITY_CHECKS = ("change-budget", "file-length", "structure")
TEST_CHECKS = ("pytest", "coverage", "diff-cover")
STYLE_CHECKS = ("ruff", "pyright", "pylint", "wemake", "xenon", "radon")
ARCHITECTURE_CHECKS = ("tach", "import", "architecture")
SECURITY_CHECKS = ("pip-audit", "secret", "gitleaks", "bandit", "osv", "trivy", "license")
DOCS_CHECKS = ("interrogate", "markdown", "yaml", "toml", "jsonschema", "docs")
DIAGNOSTIC_CHECKS = ("doctor", "guidance", "artifact", "diagnostic")
MUTATION_CHECKS = ("mutmut", "mutation")
