#!/usr/bin/env python3
"""Fail when Python files exceed repository size limits.

Default behavior:
- If explicit paths are passed, check those paths.
- Otherwise, check tracked Python files when Git is available.
- Otherwise, fall back to scanning configured file_length_paths.

The check reports only oversized files and exits nonzero when any file violates
limits. Generated files are skipped when they contain common generated-file
markers near the top.
"""

from __future__ import annotations

import argparse
import subprocess  # nosec B404
import sys
from pathlib import Path

from scripts.guardrail_config import load_config

EXCLUDED_DIRS = frozenset(
    (
        ".git",
        ".hg",
        ".svn",
        ".venv",
        "venv",
        "env",
        "__pycache__",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".tox",
        "build",
        "dist",
        "node_modules",
    )
)

GENERATED_MARKERS = (
    "@generated",
    "generated by",
    "automatically generated",
    "do not edit",
)


def parse_args(argv: list[str]) -> argparse.Namespace:
    """Parse file-length command-line options."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("paths", nargs="*", help="Specific files or directories to check.")
    parser.add_argument(
        "--root", action="append", help="Default scan root. May be repeated or comma-separated."
    )
    parser.add_argument("--max-physical", type=int)
    parser.add_argument("--max-source", type=int)
    parser.add_argument(
        "--changed-only",
        action="store_true",
        help="Check Python files changed relative to HEAD.",
    )
    parser.add_argument(
        "--include-generated",
        action="store_true",
        help="Do not skip files marked as generated.",
    )
    return parser.parse_args(argv)


def is_excluded(path: Path) -> bool:
    """Return whether a path lives under an ignored tool/cache directory."""

    return any(part in EXCLUDED_DIRS for part in path.parts)


def is_generated(path: Path) -> bool:
    """Return whether a file advertises itself as generated near the top."""

    try:
        head = "\n".join(path.read_text(encoding="utf-8", errors="replace").splitlines()[:10])
    except OSError:
        return False
    lowered = head.lower()
    return any(marker in lowered for marker in GENERATED_MARKERS)


def git_files(command: list[str]) -> list[Path]:
    """Return Python paths from a git command, or an empty list on failure."""

    try:
        result = subprocess.run(  # nosec B603
            command,
            text=True,
            capture_output=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return []

    return [Path(line) for line in result.stdout.splitlines() if line.endswith(".py")]


def parse_csv_like(values: list[str] | None) -> list[str]:
    """Normalize repeated comma-separated path options."""

    if not values:
        return []
    items: list[str] = []
    for value in values:
        items.extend(part.strip() for part in value.split(","))
    return [item.rstrip("/") or "." for item in items if item]


def expand_paths(paths: list[str], changed_only: bool) -> list[Path]:
    """Resolve explicit, changed-only, tracked, or configured scan targets."""

    if changed_only:
        return changed_python_paths()

    if paths:
        return expand_explicit_paths(paths)

    tracked = git_files(["git", "ls-files", "*.py"])
    if tracked:
        return tracked

    return configured_file_length_paths()


def changed_python_paths() -> list[Path]:
    """Return Python files changed against HEAD."""

    return git_files(["git", "diff", "--name-only", "HEAD", "--", "*.py"])


def expand_explicit_paths(paths: list[str]) -> list[Path]:
    """Expand explicit file and directory arguments into Python files."""

    expanded: list[Path] = []
    for raw in paths:
        path = Path(raw)
        if path.is_dir():
            expanded.extend(path.rglob("*.py"))
        elif path.suffix == ".py":
            expanded.append(path)
    return expanded


def configured_file_length_paths() -> list[Path]:
    """Expand configured fallback roots into Python files."""

    expanded: list[Path] = []
    for root_raw in load_config().file_length_paths:
        root = Path(root_raw)
        if root.exists():
            expanded.extend(root.rglob("*.py"))
    return expanded


def count_lines(path: Path) -> tuple[int, int]:
    """Return physical and source-line counts for one Python file."""

    physical = 0
    source = 0

    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        physical += 1
        stripped = line.strip()

        if not stripped:
            continue
        if stripped.startswith("#"):
            continue

        source += 1

    return physical, source


def eligible_python_paths(paths: list[Path], include_generated: bool) -> list[Path]:
    """Deduplicate paths and filter to checkable Python files."""

    eligible: list[Path] = []
    seen: set[Path] = set()
    for path in paths:
        path = path.resolve() if path.is_absolute() else path
        if path in seen:
            continue
        seen.add(path)

        if not path.exists() or path.suffix != ".py" or is_excluded(path):
            continue
        if not include_generated and is_generated(path):
            continue

        eligible.append(path)
    return eligible


def length_failures(paths: list[Path], max_physical: int, max_source: int) -> list[str]:
    """Return file-length failures for eligible Python files."""

    failures: list[str] = []
    for path in paths:
        physical, source = count_lines(path)
        if physical > max_physical or source > max_source:
            failures.append(
                f"{path}: {physical} physical lines, {source} source lines "
                f"(limits: {max_physical} physical, {max_source} source)"
            )
    return failures


def print_failures(failures: list[str]) -> None:
    """Print file-length failures with a refactoring-oriented hint."""

    print("File length check failed:\n")
    for failure in failures:
        print(f"  {failure}")
    print("\nSplit oversized files by responsibility instead of suppressing this check.")


def main(argv: list[str]) -> int:
    """Run the file-length check and return a process exit code."""

    args = parse_args(argv)
    config = load_config()
    configured_roots = parse_csv_like(args.root)
    paths = args.paths or configured_roots
    max_physical = args.max_physical or config.file_length_max_physical
    max_source = args.max_source or config.file_length_max_source
    expanded = expand_paths(paths, args.changed_only)
    eligible = eligible_python_paths(expanded, args.include_generated)
    failures = length_failures(eligible, max_physical, max_source)

    if failures:
        print_failures(failures)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
