#!/usr/bin/env python3
"""Fail when Python files exceed repository size limits.

Default behavior:
- If explicit paths are passed, check those paths.
- Otherwise, check tracked Python files when Git is available.
- Otherwise, fall back to scanning configured file_length_paths.

The check reports only oversized files and exits nonzero when any file violates
limits. Generated files are skipped when they contain common generated-file
markers near the top.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

from guardrail_config import load_config

DEFAULT_MAX_PHYSICAL_LINES = 600
DEFAULT_MAX_SOURCE_LINES = 450

EXCLUDED_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".venv",
    "venv",
    "env",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    "build",
    "dist",
    "node_modules",
}

GENERATED_MARKERS = (
    "@generated",
    "generated by",
    "automatically generated",
    "do not edit",
)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("paths", nargs="*", help="Specific files or directories to check.")
    parser.add_argument("--root", action="append", help="Default scan root. May be repeated or comma-separated.")
    parser.add_argument("--max-physical", type=int, default=DEFAULT_MAX_PHYSICAL_LINES)
    parser.add_argument("--max-source", type=int, default=DEFAULT_MAX_SOURCE_LINES)
    parser.add_argument(
        "--changed-only",
        action="store_true",
        help="Check Python files changed relative to HEAD.",
    )
    parser.add_argument(
        "--include-generated",
        action="store_true",
        help="Do not skip files marked as generated.",
    )
    return parser.parse_args(argv)


def is_excluded(path: Path) -> bool:
    return any(part in EXCLUDED_DIRS for part in path.parts)


def is_generated(path: Path) -> bool:
    try:
        head = "\n".join(path.read_text(encoding="utf-8", errors="replace").splitlines()[:10])
    except OSError:
        return False
    lowered = head.lower()
    return any(marker in lowered for marker in GENERATED_MARKERS)


def git_files(command: list[str]) -> list[Path]:
    try:
        result = subprocess.run(
            command,
            text=True,
            capture_output=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return []

    return [Path(line) for line in result.stdout.splitlines() if line.endswith(".py")]


def parse_csv_like(values: list[str] | None) -> list[str]:
    if not values:
        return []
    items: list[str] = []
    for value in values:
        items.extend(part.strip() for part in value.split(","))
    return [item.rstrip("/") or "." for item in items if item]


def expand_paths(paths: list[str], changed_only: bool) -> list[Path]:
    if changed_only:
        return git_files(["git", "diff", "--name-only", "HEAD", "--", "*.py"])

    if paths:
        expanded: list[Path] = []
        for raw in paths:
            path = Path(raw)
            if path.is_dir():
                expanded.extend(path.rglob("*.py"))
            elif path.suffix == ".py":
                expanded.append(path)
        return expanded

    tracked = git_files(["git", "ls-files", "*.py"])
    if tracked:
        return tracked

    expanded: list[Path] = []
    for root_raw in load_config().file_length_paths:
        root = Path(root_raw)
        if root.exists():
            expanded.extend(root.rglob("*.py"))
    return expanded


def count_lines(path: Path) -> tuple[int, int]:
    physical = 0
    source = 0

    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        physical += 1
        stripped = line.strip()

        if not stripped:
            continue
        if stripped.startswith("#"):
            continue

        source += 1

    return physical, source


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    configured_roots = parse_csv_like(args.root)
    paths = args.paths or configured_roots
    failures: list[str] = []

    seen: set[Path] = set()
    for path in expand_paths(paths, args.changed_only):
        path = path.resolve() if path.is_absolute() else path
        if path in seen:
            continue
        seen.add(path)

        if not path.exists() or path.suffix != ".py" or is_excluded(path):
            continue
        if not args.include_generated and is_generated(path):
            continue

        physical, source = count_lines(path)
        if physical > args.max_physical or source > args.max_source:
            failures.append(
                f"{path}: {physical} physical lines, {source} source lines "
                f"(limits: {args.max_physical} physical, {args.max_source} source)"
            )

    if failures:
        print("File length check failed:\n")
        for failure in failures:
            print(f"  {failure}")
        print("\nSplit oversized files by responsibility instead of suppressing this check.")
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
