"""Safety checks for file context expansion."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

MAX_JSON_LINE_LENGTH = 2_000
MAX_MINIFIED_JSON_LINES = 2
TEXT_SAMPLE_BYTES = 4_096
LOCK_FILE_NAMES = frozenset(
    (
        "package-lock.json",
        "pnpm-lock.yaml",
        "poetry.lock",
        "uv.lock",
        "Pipfile.lock",
    ),
)
REFUSED_SUFFIXES = frozenset((".ipynb", ".pyc", ".pyo"))
REFUSED_PARTS = frozenset(
    (
        ".git",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".tox",
        ".venv",
        "__pycache__",
        "build",
        "dist",
        "htmlcov",
        "node_modules",
        "venv",
    ),
)
GENERATED_MARKERS = ("generated", "autogenerated", "do not edit")


@dataclass(frozen=True)
class FileSafety:
    """File context safety decision."""

    allowed: bool
    reason: str
    path: Path


def inspect_file(path: Path) -> FileSafety:
    """Return safety decision for a file path."""

    path_decision = inspect_path(path)
    if path_decision is not None:
        return path_decision
    raw = read_file_bytes(path)
    if isinstance(raw, FileSafety):
        return raw
    return inspect_text(path, raw)


def inspect_path(path: Path) -> FileSafety | None:
    """Return path-level refusal when applicable."""

    if path.is_symlink():
        return denied(path, "symlink")
    if refused_path(path):
        return denied(path, "refused generated/cache/lock path")
    return None


def read_file_bytes(path: Path) -> bytes | FileSafety:
    """Return file bytes or refusal."""

    try:
        return path.read_bytes()
    except OSError as exc:
        return denied(path, f"unreadable: {exc}")


def inspect_text(path: Path, raw: bytes) -> FileSafety:
    """Return content-level safety decision."""

    if is_binary(raw):
        return denied(path, "binary file")
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        return denied(path, "non-UTF-8 file")
    if looks_generated(text):
        return denied(path, "generated file")
    if looks_minified_json(path, text):
        return denied(path, "minified JSON")
    return FileSafety(True, "ok", path)


def denied(path: Path, reason: str) -> FileSafety:
    """Return denied file safety decision."""

    return FileSafety(False, reason, path)


def refused_path(path: Path) -> bool:
    """Return whether path should never be expanded directly."""

    return (
        path.name in LOCK_FILE_NAMES
        or path.suffix in REFUSED_SUFFIXES
        or any(part in REFUSED_PARTS for part in path.parts)
    )


def is_binary(raw: bytes) -> bool:
    """Return whether byte sample appears binary."""

    return b"\x00" in raw[:TEXT_SAMPLE_BYTES]


def looks_generated(text: str) -> bool:
    """Return whether text appears generated."""

    first_lines = "\n".join(text.splitlines()[:5]).lower()
    return any(marker in first_lines for marker in GENERATED_MARKERS)


def looks_minified_json(path: Path, text: str) -> bool:
    """Return whether JSON text is likely minified and too dense."""

    if path.suffix != ".json":
        return False
    lines = text.splitlines()
    return len(lines) <= MAX_MINIFIED_JSON_LINES and any(
        len(line) > MAX_JSON_LINE_LENGTH for line in lines
    )
